### PR TITLE
(fix)test: added blank lines to README to force a new build

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2210-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2210-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@ldimaggi do you need this merged? or is it for testing something? We have merged a bunch of stuff since you submitted it.

**Comment by ldimaggi** [comment]
No - this can be safely ignored. Thanks for asking! I will close the PR.

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2210-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2210-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
