### PR TITLE
fix(import.wizard): display warning for overriden files

### PR DESCRIPTION
**Pull request by corinnekrych**
Fixes https://github.com/openshiftio/openshift.io/issues/671

### CODE REVIEW

**Comment by joshuawilson** [comment]
@corinnekrych it appears that there is a unit test failure.

**Comment by corinnekrych** [comment]
@joshuawilson There is 2 tests that are causing an ERROR (without failing the tests though). Those are unit test for the run-time console. Do you have any idea why they failing ?

The failure on jenkins CI seems to be a jenkins issue :) :
```
java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Cannot contact jenkins-slave-thkgd-0nqbj: java.lang.RuntimeException: java.io.IOException: Pipe not connected
```
It's completely unrelated to the small change in the wizard UI
Let me rebase and trigger another build.

**Comment by corinnekrych** [comment]
@joshuawilson @kbsingh now tests are ok but:
```
+ echo 'BUILD TIMEOUT'
BUILD TIMEOUT
```
Any idea why this is happening?

**Comment by kbsingh** [comment]
extending the timeout now, give it about 30 - 45 min and you should be all set

**Comment by corinnekrych** [comment]
[test]

**Comment by jstrachan** [comment]
ok to test

**Comment by kbsingh** [comment]
bumped to 50m here : https://github.com/almighty/almighty-jobs/pull/302 this is now applied.

**Pull request merged**
