### PR TITLE
fix(planner): board view navigation is removed temporarily

### PR DESCRIPTION
**Pull request by sanbornsen**
Board view is removed temporarily till the summit. After that board view is likely to be refactored and added back with a new design and a number of new features. 

Related issue - https://openshift.io/openshiftio/openshiftio/plan/detail/1945

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sanbornsen for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by sanbornsen** [comment]
[test]

**Comment by joshuawilson** [comment]
@sanbornsen you need to update the tests. You see Ike above is crying because you didn't fix the tests.

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2795-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2795-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2795-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2795-fabric8-ui.badger.fabric8.io

**Pull request merged**
