### PR TITLE
fix(tests): use headless chrome instead of phantomjs for unit tests

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR
 - Removed PhantomJS from package.json and package-lock.json
 - Updates karma.conf.js file to use headless chrome instead of phantomjs

### CODE REVIEW

**Comment by aptmac** [comment]
Test failures: https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-ui/detail/PR-3280/1/pipeline#step-38-log-725

```
SUMMARY:
✔ 796 tests completed
ℹ 7 tests skipped
✖ 2 tests failed

FAILED TESTS:
  CodebasesComponent
    sorting codebases
      ✖ should sort codebases by repository created at
        HeadlessChrome 62.0.3202 (Linux 0.0.0)
      Expected 'alpha' to be 'beta'.
          at UserContext.<anonymous> (config/spec-bundle.js:343307:60)
          [ ... ]

      ✖ should sort codebases by repository pushed at
        HeadlessChrome 62.0.3202 (Linux 0.0.0)
      Expected 'alpha' to be 'beta'.
          at UserContext.<anonymous> (config/spec-bundle.js:343321:60)
          [ ... ]
```

Additionally, the first character of commit subject shouldn't be capitalized [[0]](https://github.com/fabric8-ui/fabric8-ui#subject)

[0] https://github.com/fabric8-ui/fabric8-ui#subject

**Comment by jarifibrahim** [comment]
@aptmac How did the test failed on GKE (fabric8-cd) but passed on CiCO?

**Comment by joshuawilson** [comment]
This doesn't go all that is needed to move to Chrome. It is also something that will be fixed in the upgrade. 

If you can do everything that is needed, then we can merge it. If not, please close this.

**Comment by jarifibrahim** [comment]
>If you can do everything that is needed, then we can merge it. If not, please close this.

I am not sure what else needs to be fixed apart from the tests. I'll close this one.

**Pull request closed without merging**
