### PR TITLE
fix(space-description): fix description text not updating when using …

### PR DESCRIPTION
**Pull request by aptmac**
…save button

fixes https://github.com/openshiftio/openshift.io/issues/2879 [0]

This PR fixes an issue where trying to update the descriptor text of a Space using the buttons would not work. However, pressing the enter button would properly update the description, (it's just the button that's not working). The result of this was trying to grab the textarea contents outside of the textarea tag would return an undefined value, so `saveDescription()` would be trying to update an undefined value [1]; the enter-keyclick was inside of the textarea tag [2], which is why `onUpdateDescription` would be passed the correct value. 

To amend this, the textarea now binds to a variable in the component which is able to be retrieved by the button. There are also two methods (`onUpdateDescription`[3] and `saveDescription()[1]` which do the same thing, so they have been combined into the later. Additionally, the placeholder text has been moved to a variable as well to reduce duplication. 

[0] https://github.com/openshiftio/openshift.io/issues/2879
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts#L82
[2] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html#L51
[3] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts#L74

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@aptmac was this tested on the current production space dashboard, or the updated version under the Experimental Feature flag?

**Comment by aptmac** [comment]
@mindreeper2420 the current space dashboard;
space-description

**Comment by mindreeper2420** [comment]
@aptmac can you check this fix against the experimental version too? I just want to make sure that the issue won't come up again when it is released.

**Comment by aptmac** [comment]
I tested it against the experimental version, and ended up getting a better picture of what was going on. 

It works in experimental, but not in default. Both of the description textareas are referenced to as `#description`, but the experimental one is first in the html. When using the default controls, hitting the submit button would try to grab the text from the experimental textarea, which is why it was getting an undefined value. The fix here was to make the two textareas unique from one another so there is no miscommunication between the textareas and the component. I've referred the current one `descriptiondefault` and the experimental one `descriptionexperimental`.

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by dlabrecq** [comment]
I agree the fix works, but a lot of changes were made to handle it. Not only to the HTML template, but the component. Now the component must handle two unique ViewChild objects.

IMO, that should be fixed now. However, if an issue is created to track the issue, if @joshuawilson wants to merge as is, I'll defer.

**Comment by jiekang** [comment]
Okay, that sounds reasonable to me. This PR can either be reworked or closed with a new PR for the separation.

**Comment by aptmac** [comment]
I played around with separation into two widgets, and currently have this branch where it's working [0]. (I named the new widget 'edit-space-description-widget-old' just so it'd appear underneath the original widget in my file explorer, that name can be changed). 

It's cleaner in terms of when we will need to remove the old functionality it will be a quick(er) deletion, but there isn't any difference in the functionality so it's basically just a duplication of logic. Additionally, having all of these widgets living side-by-side is interesting, because analyze-overview.module will be importing and init-ing both of them everytime the analyze page is loaded. It's probably not a big deal at the moment because it would only be the work-items and description widgets having different widgets (and it's temporary even until the old ones get phased out), but if this becomes more common then loading the analyze page could be a lot more costly than it has to be.

Let me know your thoughts, I can close this PR and open up a new one for the separate widget branch.

[0] https://github.com/aptmac/fabric8-ui/commit/1b6816e9719753c16d1d3742a993de74462888ff

**Comment by jiekang** [comment]
For what it's worth, the last time I checked, the Analyze page is already bloated either way because the components are being loaded by Angular even if they're hidden and not in the DOM. See https://github.com/openshiftio/openshift.io/issues/2908

Hmm, reported 28 days ago so it's highly likely to have been changed.

**Comment by aptmac** [comment]
Here I've separated the original widget into two different ones. I kept the name '-old' because it makes it easier to distinguish in the code and file explorer which widget is which when it comes time to remove the old one (or make any potential tweaks).

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-11 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-12 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-14 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2800-15 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2800-fabric8-ui.badger.fabric8.io

**Pull request merged**
