### PR TITLE
Import runtime console

### PR DESCRIPTION
**Pull request by joshuawilson**
This will bring the runtime-console complete over to the main UI.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@joshuawilson referencing the `.scss` file won't work, as there is no Sass builder. I did not realize that the Sass files were dropped into the shared directory when this import was started. I'll fix this and verify that the correct files are imported.

**Comment by joshuawilson** [comment]
@mindreeper2420 what is there left to fix?

**Comment by joshuawilson** [comment]
we need @rawlingsj to take a look at why the build is failing on the last step

**Comment by mindreeper2420** [comment]
@joshuawilson there were leftover `.scss` files in the assets/shared directory, as well as an `_icons.less` file from the runtime console that wasn't included in the overall build. I can fix those and add them to the branch for this PR, if you'd like.

**Comment by joshuawilson** [comment]
@mindreeper2420 let me see if I can get this merged. Then you can send a PR for that fix.

**Comment by fabric8cd** [comment]
@null fabric8/fabric8-ui:SNAPSHOT-PR-1877-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1877-fabric8-ui.badger.fabric8.io

**Pull request merged**
