### PR TITLE
Update Dockerfile base image tag fabric8/fabric8-openshift-nginx to SNAPSHOT-PR-15-15

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by fabric8cd** [comment]
[merge]

**Comment by fabric8cd** [comment]
@null fabric8/fabric8-ui:SNAPSHOT-PR-1880-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1880-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1880-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1880-fabric8-ui.badger.fabric8.io

**Comment by hectorj2f** [comment]
I am closing this PR. It was just a test

**Pull request closed without merging**
