### PR TITLE
fix(header): remove duplicate of spaces

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses https://openshift.io/openshiftio/Openshift_io/plan/detail/782 and https://github.com/openshiftio/openshift.io/issues/4325, which does the following:
1. Renames the `Account Home` to `Home`
2. Removes `View all Spaces`
3. Renames `My Spaces` to `Spaces` and updates the icon

Reference mock-up: https://redhat.invisionapp.com/share/5SODKG576EU#/screens/323350840

Before:
before

After:
after

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @aptmac for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by aptmac** [comment]
@serenamarie125 Yes that should be a quick fix. It's a small capitalization fix, so this shouldn't impact documentation or screenshots anywhere?

**Comment by joshuawilson** [comment]
@serenamarie125 that kind of change is not related to this change and should be done a new PR. It is not a valid reason to block the PR.

**Pull request merged**
