### PR TITLE
fix(animations): add animations to the UI

### PR DESCRIPTION
**Pull request by mindreeper2420**
add animations to the header, links and tab navigation

### CODE REVIEW

**Comment by mindreeper2420** [comment]
[test]

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1715-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1715-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1715-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1715-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1715-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1715-fabric8-ui.badger.fabric8.io

**Pull request merged**
