### PR TITLE
Enable email update

### PR DESCRIPTION
**Pull request by alexeykazakov**
We will need to enable email updates since we now fully support email verification on the backend side.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
[test]

**Comment by joshuawilson** [comment]
looks like a lint error was introduced, I need to clear it and then you can rebase

**Comment by joshuawilson** [comment]
looks like a build issue not a lint error

**Comment by fabric8cd** [comment]
@alexeykazakov fabric8/fabric8-ui:SNAPSHOT-PR-2377-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2377-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@alexeykazakov fabric8/fabric8-ui:SNAPSHOT-PR-2377-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2377-fabric8-ui.badger.fabric8.io

**Pull request merged**
