### PR TITLE
fix(pipelines): correct application pipelines link URL

### PR DESCRIPTION
**Pull request by andrewazores**
fixes https://github.com/openshiftio/openshift.io/issues/2334

See also https://github.com/fabric8-ui/fabric8-ui/pull/2589 , which is very similar. In this component the `contextPath` already contains the current space, whereas on the homepage for the component in #2589, the buildconfig space label must also be used to construct the path (since there is no active space on the homepage).

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2590-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2590-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
@andrewazores while you're in this area: the build link also looks broken in production and local master.

```
pipelines-widget.component.html:
[...]
<a [href]="buildconfig.openShiftConsoleUrl" target="_blank" 
[...]
```

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2590-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2590-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
@jiekang hmm... build links seem to work for me. Can you file a new issue for it if it's reproducible?

**Pull request merged**
