### PR TITLE
Pass additional pipeline info to short report component 

### PR DESCRIPTION
**Pull request by jyasveer**
Pass additional pipeline info to short report component for the dashboard widget

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-2307-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2307-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-2307-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2307-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
