### PR TITLE
fix(home): clean up unused code

### PR DESCRIPTION
**Pull request by jiekang**
This is includes cleanup of unused imports, unused variables, subscriptions and initialization.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jiekang for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by andrewazores** [comment]
This duplicates some work I have done here as well: https://github.com/fabric8-ui/fabric8-ui/pull/3166

Merging this one first might make my rebase a bit painful...

**Comment by jiekang** [comment]
@andrewazores I don't mind rebasing. If you'd like to incorporate changes here into your PR, I also don't mind. Whatever you think will be the least painful will be good for me.

**Comment by joshuawilson** [comment]
We did have the FF on the dashboard so that we could flag widgets. Does this remove that support?

**Comment by andrewazores** [comment]
No, that should continue working. The widgets are feature flagged by using the f8-feature-toggle component, so the HomeComponent itself doens't actually need to inject the FeatureTogglesService - the f8-feature-toggle component handles it on its own.

**Pull request merged**
