### PR TITLE
feat(profile): navigate home on successful tenant update

### PR DESCRIPTION
**Pull request by c-koehler**
fixes https://github.com/openshiftio/openshift.io/issues/1566

### CODE REVIEW

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2300-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2300-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
The issue called for a simple redirect. Since you went to all the effort to make it fancy we need to get UX to review it now.
@catrobson can you please have someone look at this.

**Comment by mindreeper2420** [comment]
@c-koehler how do I get all of the stages to appear one at a time, so that they can be viewed? From the speed of the update, I could only catch part of the refresh action.

**Comment by joshuawilson** [comment]
I don't think you can or every will see them.

**Comment by c-koehler** [comment]
@mindreeper2420 One thing I could do is to take screenshots for you, or I could make a quick shell script for you to run that would modify the code currently so it would display them for you easily on a local copy. If there's anything you need me to do to make your life easier let me know.

**Comment by joshuawilson** [comment]
@c-koehler please get on a call and review this with @mindreeper2420 
We need UXD to sign off on this.

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2300-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2300-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2300-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2300-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@mindreeper2420 can you please review the design of this with @c-koehler?

**Pull request merged**
