### PR TITLE
fix(add-app-overlay): fix null id error when creating app from non-sp…

### PR DESCRIPTION
**Pull request by aptmac**
…ace associated page

This PR addresses [issue 3589](https://github.com/openshiftio/openshift.io/issues/3589), in which the add-app-overlay will encounter a null 'id' error when creating a space from a non-space associated page (example: view all spaces, profile, my spaces, account home, etc.). This is because the `space.id` value is being retrieved from an observable that may not yet have the value, and at least from what I've seen consistently is that the correct `space.id` is emitted after the TypeError has already occurred - which doesn't really help us. 

This PR makes a check to see if the `space.id` value exists, and continues with the expected functionality is so. If the value is null, then an empty observable is passed into the subscribe which will stop the code from acting on the null value.

[0] https://github.com/openshiftio/openshift.io/issues/3589
[1] https://github.com/openshiftio/openshift.io/issues/3657
[1] https://github.com/fabric8-ui/fabric8-ui/blob/f301d52a9b5441c129498550144ac223f83e7a75/src/app/space/add-app-overlay/add-app-overlay.component.ts#L50

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @aptmac for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by aptmac** [comment]
It looks like there are a bunch of duplicate issues related to this, for tracking purposes they are listed here:

https://github.com/openshiftio/openshift.io/issues/3586
https://github.com/openshiftio/openshift.io/issues/3589
https://github.com/openshiftio/openshift.io/issues/3646
https://github.com/openshiftio/openshift.io/issues/3657
https://github.com/openshiftio/openshift.io/issues/3658

**Comment by joshuawilson** [comment]
Does this need the tests updated?

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2945-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2945-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2945-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2945-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2945-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2945-fabric8-ui.badger.fabric8.io

**Pull request merged**
