### PR TITLE
fix(runtime): remove apps-list-toolbar

### PR DESCRIPTION
**Pull request by andrewazores**
remove toolbar containing unimplmented sort/filter buttons which caused the application to return to
_home on click

closes openshiftio/openshift.io#489

### CODE REVIEW

**Comment by joshuawilson** [comment]
you yanked it out by the root ;)

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2255-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2255-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2255-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2255-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
The code looks fine to me and does what's asked. As far as I can tell, none of the component functions are implemented so I don't mind it being removed completely.

I'm not sure if others may have exceptions against removing the whole component. @joshuawilson?

**Comment by andrewazores** [comment]
[test]

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2255-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2255-fabric8-ui.badger.fabric8.io

**Pull request merged**
