### PR TITLE
fix(accounthome): update font and text for Acount Home page

### PR DESCRIPTION
**Pull request by junezhang**
## Description
The purpose of this is to as following:

- fix work item empty state font
- update text on the "recent active pipelines"
- update the capitalization to be same with[ PatternFly Capitalization Guideline](https://www.patternfly.org/styles/terminology-and-wording/#capitalization)

Related to this story:
https://github.com/fabric8-ui/fabric8-ux/issues/653

## Link to rawgit and/or image

textupdate

@catrobson Please help to review about this one, thanks.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@junezhang fabric8/fabric8-ui:SNAPSHOT-PR-1988-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1988-fabric8-ui.badger.fabric8.io

**Comment by catrobson** [comment]
Some more changes have been requested on the issue.

**Comment by mindreeper2420** [comment]
@catrobson can you start a review and submit as 'Request Changes'? That way, it won't show up as all green :-)

**Comment by joshuawilson** [comment]
You will also need to change the commit to use a single word in the parenthesis. If you need help doing that, please ping me.

**Comment by junezhang** [comment]
@catrobson @Essjaysee
Based on Sj's feedback, I've update the text, please have a review. the below is screenshot for the latest updating.
screen shot 2017-09-11 at 12 18 41 pm

**Comment by joshuawilson** [comment]
[test]

**Comment by catrobson** [comment]
@junezhang can you see why there is a little difference in the height for where the icon and text start in these widgets?  Its visually distracting that the Work Items and Active Pipelines in-card text don't start at the same height even though there is the same amount of content.  Ideally I think it would be great if these were top-aligned to start at the same place.  @mindreeper2420 not sure how the alignment works from PatternFly to factor that in.

**Comment by mindreeper2420** [comment]
@catrobson the reason for the height differences in the starting position for the icons/text is that the cards are using a vertical alignment to center the content on the Y-axis. The cards are OSIO components based off of PatternFly, so not changes to PatternFly are needed.

**Comment by catrobson** [comment]
@mindreeper2420 so shouldn't the latter two cards have the same height to start if the centered on Y-axis is working correctly?  Regardless, if we've already deviated from PatternFly, what do you think about doing a top-alignment with a standard padding in place?

**Comment by mindreeper2420** [comment]
@catrobson they wouldn't, due to the header being one line on the first card, and two lines on the second. The padding/margin associated with headings are doing funny things with the calculations.

A standard top-alignment would work well for all of these, since the headers and paragraphs are not kept to the same number of lines for each card. Would that be best as a separate issue, filed as a bug?

**Comment by catrobson** [comment]
@mindreeper2420 gotcha, thanks for the explanation.  Yes, I'll file this as a separate bug for updating.

**Comment by joshuawilson** [comment]
[test]

**Comment by mindreeper2420** [comment]
[test]

**Comment by mindreeper2420** [comment]
@joshuawilson I ran tests and builds locally and everything passed, but the builds keeps failing on the server. Any ideas?

**Comment by joshuawilson** [comment]
I'll take a look.

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@kbsingh I don't know why this one doesn't finish and times out.

**Comment by fabric8cd** [comment]
@junezhang fabric8/fabric8-ui:SNAPSHOT-PR-1988-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1988-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
