### PR TITLE
Use latest tag to get fabric8-openshift-nginx docker image

### PR DESCRIPTION
**Pull request by hectorj2f**
We need to get the latest docker image for f8-openshift-nginx until we automatize this change setting the right version tag.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@hectorj2f fabric8/fabric8-ui:SNAPSHOT-PR-1866-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1866-fabric8-ui.badger.fabric8.io

**Comment by aslakknutsen** [comment]
[test]

**Comment by rawlingsj** [comment]
FWIW it's best to use a tagged version rather than :latest.  When building the fabric8 UI with a base image of latest will mean if the node that builds the image already has a locally pulled :latest version then that is used.  i.e. a docker pull is not always performed. 

Best to use the pipelines on fabric8-openshift-nginx to make an automated PR on this repo of the any new release tags.

**Comment by hectorj2f** [comment]
> FWIW it's best to use a tagged version rather than :latest. When building the fabric8 UI with a base image of latest will mean if the node that builds the image already has a locally pulled :latest version then that is used. i.e. a docker pull is not always performed.

@rawlingsj that is the plan, but we need this running now. However, I might say this approach or reusing an existing latest version is wrong. It should force the pull of the image

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@hectorj2f fabric8/fabric8-ui:SNAPSHOT-PR-1866-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1866-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@hectorj2f there is no change, what is this supposed to do?

**Comment by hectorj2f** [comment]
@joshuawilson True! I pushed the changes in the other PR

**Pull request closed without merging**
