### PR TITLE
added unit tests in utilities package

### PR DESCRIPTION
**Pull request by sathishvj**
Trying out a PR with a couple of simple tests on the clone function.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2009-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2009-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@sathishvj please rebase your commit to use the commit syntax that will trigger a release. Instructions can be found at https://github.com/fabric8-ui/fabric8-ui#continuous-delivery--semantic-releases

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2009-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2009-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2009-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2009-fabric8-ui.badger.fabric8.io

**Pull request merged**
