### PR TITLE
fix(login-service): remove unused imports

### PR DESCRIPTION
**Pull request by jiekang**
The error and context services are unused. This PR removes them to keep the code clean.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jiekang for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by alien-ike** [comment]
Hey @andrewazores! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer, but not pull request creator for this command to take an effect.

**Comment by bartoszmajsak** [comment]
@andrewazores we have it fixed and will roll out today https://github.com/arquillian/ike-prow-plugins/issues/118

**Comment by bartoszmajsak** [comment]
@andrewazores this should not be the problem anymore. new version is out

**Pull request merged**
