### PR TITLE
fix(version): update fabric8-stack-analysis-ui to 0.4.0

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1951-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1951-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@arunkumars08 so this PR changes it to 4.0 from 5.1, and you closed the PR for 6.0. I'm confused as to what number it should be. Normally I would just close a PR that downgrades.

**Comment by arunkumars08** [comment]
@joshuawilson Actually PR for 0.6.0 was automatically closed by fabric8cd. I can close this as it is outdated.

**Comment by arunkumars08** [comment]
@joshuawilson Actually the PR for 0.6.0 was automatically closed by fabric8cd. Moreover the latest version is already merged into master. Other versions can be closed. Thanks

**Comment by arunkumars08** [comment]
@Joshua I think you can close all the PRs generated. The latest is already
merged in. Thanks

**Pull request closed without merging**
