### PR TITLE
fix(deployments): update error messages to be more user friendly

### PR DESCRIPTION
**Pull request by jiekang**
This addresses https://github.com/openshiftio/openshift.io/issues/2713

The error messages for http specific errors are made more user friendly. Tests are added to verify all paths that http error handling is involved, but technically not all paths that eventually lead to the http error handling.

Thoughts? I think there is a lot of room for different implementation forms and different error messages. Any suggestions are welcomed and very much appreciated!

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@jiekang can you list out the errors messages that you created so that they can be looked at easier than going through the typescript file?

**Comment by jiekang** [comment]
The notifications are a header + message combination. Header for the area, message for the error.

```
+              let header: string = 'Cannot get applications';
+              let header: string = 'Cannot get environments';
+              let header: string = 'Cannot get latest application statistics';
+        let header: string = 'Cannot get initial application statistics';
```

```
+
+    if (response.status === 403 || response.status === 401) {
+      message = 'Not authorized to access service';
+      type = NotificationType.DANGER;
+    } else if (response.status === 404) {
+      message = 'Service unavailable. Please try again later';
+      type = NotificationType.WARNING;
+    } else if (response.status === 500) {
+      message = 'Service error. Please try again later';
+      type = NotificationType.WARNING;
+    } else {
+      message = 'Unknown error. Please try again later';
+      type = NotificationType.DANGER;
+    }
```

**Comment by joshuawilson** [comment]
Please rebase.

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2953-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2953-fabric8-ui.badger.fabric8.io

**Pull request merged**
