### PR TITLE
fix(codebases): updating message for workspace migration

### PR DESCRIPTION
**Pull request by ibuziuk**
rh-che issue https://github.com/redhat-developer/rh-che/issues/448
Updating message to be suitable for che 5 -> che 6 workspace migration

### CODE REVIEW

**Comment by ibuziuk** [comment]
[test]

**Comment by joshuawilson** [comment]
we need to get https://github.com/fabric8-ui/fabric8-ui/pull/2615 merged and then this rebased on that for the build to pass

**Comment by ibuziuk** [comment]
@joshuawilson ah, ok - thanks for clarifications. Thought it is just a random failure ;-)

**Comment by fabric8cd** [comment]
@ibuziuk fabric8/fabric8-ui:SNAPSHOT-PR-2632-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2632-fabric8-ui.badger.fabric8.io

**Comment by ibuziuk** [comment]
@joshuawilson checks are passing now. Could you please review ?

**Pull request merged**
