### PR TITLE
fix(home): update content of the banner

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the content of the home dashboard banner

### CODE REVIEW

**Comment by jiekang** [comment]
Is there an issue to reference? Or a invisionapp design?

**Comment by mindreeper2420** [comment]
@joshuawilson @jiekang There is no InVision doc, but I did find a GitHub issue: https://github.com/openshiftio/openshift.io/issues/3379. It was just hidden in the sea of GitHub issues :)

**Comment by chrislessard** [comment]
Insofar as the comments on that issue are concerned, this looks good to me. It does feel a bit funny to include a screen capture of the features shrunk down in the banner - it's not really all that readable IMO? I would have been fine with just text describing the feature and a link to visit it. @catrobson What do you think of this ?

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2930-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2930-fabric8-ui.badger.fabric8.io

**Pull request merged**
