### PR TITLE
Status: Add the combineLatest operator for RxJS

### PR DESCRIPTION
**Pull request by dlabrecq**
Added the combineLatest operator of RxJS for the status component.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2156-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2156-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
now that we know how to upgrade to RxJS 5.5 I'm going to close this and use the latest

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2156-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2156-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
