### PR TITLE
fix(webpack): add dev server with increased keepAliveTimeout

### PR DESCRIPTION
**Pull request by christianvogt**
Adding an alternative dev server which increases the keepAliveTimeout to prevent errors with serving very large dev JS files that take longer than 5 seconds resulting in the following error:
`http://localhost:3000/vendor.bundle.js net::ERR_CONTENT_LENGTH_MISMATCH`

Use the following command to run the dev server:
`npm run server:dev2`

The timeout is increased by default from 5 seconds to 10 seconds and can further controlled via argument in `package.json` script or in `devserver.js`.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @christianvogt for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by corinnekrych** [comment]
@christianvogt 👍 let me merge, I've also added to our how-to wiki page a section about it - copy/pasting your description ;)

**Pull request merged**
