### PR TITLE
fix(feature-flag): anonymous browsing in context

### PR DESCRIPTION
**Pull request by corinnekrych**
fixes https://github.com/openshiftio/openshift.io/issues/2064

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Shouldn't the toggle-service deal with that?

**Comment by corinnekrych** [comment]
@aslakknutsen agreed there is another discussion on https://github.com/openshiftio/openshift.io/issues/1165#issuecomment-360796061
Here it's to fix an issue on error handling.

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2449-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2449-fabric8-ui.badger.fabric8.io

**Comment by corinnekrych** [comment]
[test]

**Pull request merged**
