### PR TITLE
feat(preboot loading screen): added OpenShift.io logo with progress bar during preboot

### PR DESCRIPTION
**Pull request by kylebuch8**
Removed the Loading... text and replaced it with an inline OpenShift.io svg and an indeterminate
progress bar. Once the app loads, the HTML and style tag that were added will be replaced with the
booted app

screen shot 2017-07-03 at 12 18 00 pm

### CODE REVIEW

**Comment by fabric8cd** [comment]
@kylebuch8 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1623-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
Why include the SVG file and the data from the file in the html?

**Comment by kylebuch8** [comment]
Including the SVG directly makes for the fastest load. If you included it as an img, then it would require a network request. Since it's just a preboot screen, I was trying to keep it simple and only require that CSS be downloaded before we show the loader. Really, the whole point is for speed to paint.

**Pull request merged**
