### PR TITLE
fix(home): remove onboarding area from home page

### PR DESCRIPTION
**Pull request by rohitkrai03**
Fixes https://github.com/openshiftio/openshift.io/issues/4376

### CODE REVIEW

**Comment by joshuawilson** [comment]
This will require @fabric8-ui/docs to update screen shots. Please view this in prod-preview.

**Comment by Preeticp** [comment]
@joshuawilson content and screenshot in the docs has been updated as per prod-preview: https://github.com/fabric8io/fabric8-online-docs/pull/432

**Comment by joshuawilson** [comment]
thanks @Preeticp

**Pull request merged**
