### PR TITLE
[WIP] support Jest

### PR DESCRIPTION
**Pull request by christianvogt**
Initial support for jest. Still trying to get all tests to pass.

Current progress:
```
Test Suites: 8 failed, 125 passed, 133 total
Tests:       21 failed, 5 skipped, 816 passed, 842 total
Snapshots:   0 total
Time:        34.847s
```

### CODE REVIEW

**Comment by corinnekrych** [comment]
First run:
```
Test Suites: 9 failed, 124 passed, 133 total
Tests:       21 failed, 5 skipped, 816 passed, 842 total
Snapshots:   0 total
Time:        254.428s
```
Second run:
```
Test Suites: 8 failed, 125 passed, 133 total
Tests:       19 failed, 5 skipped, 818 passed, 842 total
Snapshots:   0 total
Time:        33.884s, estimated 250s
```
Indeed the major gain is in the cached execution.

**Comment by christianvogt** [comment]
It's interesting that your first and second runs have different results.

Unless we change the jest transforms, you won't have to clear the cache.

It's also very easy to append a file name to the CMD in order to run a specific file only.

**Comment by christianvogt** [comment]
Test Suites: 132 passed, 132 total
Tests:       5 skipped, 837 passed, 842 total
Snapshots:   0 total
Time:        44.186s

**Comment by corinnekrych** [comment]
@christianvogt great work! We now need to clean all the unused karma dependencies and remove webpack.config.js file. I'd suggest we merge this PR to `upgrade` and then do the clean up on that branch. cc @joshuawilson

**Pull request merged**
