### PR TITLE
fix(codebases): enable backaction outlet in routing

### PR DESCRIPTION
**Pull request by corinnekrych**
fixes https://github.com/openshiftio/openshift.io/issues/3100

### CODE REVIEW

**Comment by joshuawilson** [comment]
This doesn't completely solve it.

**Comment by aptmac** [comment]
@joshuawilson what functionality doesn't get resolved? additionally, it resolves the add-work-item action issue for me too, as seen in https://github.com/openshiftio/openshift.io/issues/3021 [0].

[0] https://github.com/openshiftio/openshift.io/issues/3021

**Comment by joshuawilson** [comment]
If you click the plus for codebases, after the page changes, click on pipelines. The URL keeps the codebases URL with an ending like this `create/(pipelines//action:add-codebase)`.

We need to find the root cause.

**Comment by dlabrecq** [comment]
I build/ran this branch locally, but get a blank home page. I added name="action" manually, to a clean master branch, and encountered the same issue. 

I can see the URL change when attempting to navigate to my profile or spaces, but still get a blank page.

I don't see any errors in the console, but believe the feature flags is preventing the home page from displaying?

**Comment by joshuawilson** [comment]
I was able to trace the cause to https://github.com/fabric8-ui/fabric8-ui/pull/2691 and it appears this fix puts things back to the way they were.

**Pull request merged**
