### PR TITLE
feat(application): remove the application / environment widget from the dashboard

### PR DESCRIPTION
**Pull request by joshuawilson**
Requires https://github.com/fabric8io/fabric8-test/pull/1221 to be merged right before or after. 

analyze codeready toolchain

@fabric8-ui/docs please review the docs, this PR will change the dashboard.

As this change removes the Deployments page and Application widget, it will close all the open issues related to them.
fixes https://github.com/openshiftio/openshift.io/issues/4631
fixes https://github.com/openshiftio/openshift.io/issues/4439
fixes https://github.com/openshiftio/openshift.io/issues/3757
fixes https://github.com/openshiftio/openshift.io/issues/3637
fixes https://github.com/openshiftio/openshift.io/issues/3344
fixes https://github.com/openshiftio/openshift.io/issues/2911
fixes https://github.com/openshiftio/openshift.io/issues/2888
fixes https://github.com/openshiftio/openshift.io/issues/2754
fixes https://github.com/openshiftio/openshift.io/issues/2632
fixes https://github.com/openshiftio/openshift.io/issues/2629
fixes https://github.com/openshiftio/openshift.io/issues/2543
fixes https://github.com/openshiftio/openshift.io/issues/2529
fixes https://github.com/openshiftio/openshift.io/issues/2380
fixes https://github.com/openshiftio/openshift.io/issues/2338
fixes https://github.com/openshiftio/openshift.io/issues/2336
fixes https://github.com/openshiftio/openshift.io/issues/2113
fixes https://github.com/openshiftio/openshift.io/issues/2096
fixes https://github.com/openshiftio/openshift.io/issues/1968
fixes https://github.com/openshiftio/openshift.io/issues/1965
fixes https://github.com/openshiftio/openshift.io/issues/1964
fixes https://github.com/openshiftio/openshift.io/issues/1909
fixes https://github.com/openshiftio/openshift.io/issues/1726
fixes https://github.com/openshiftio/openshift.io/issues/4651

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @joshuawilson for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by ppitonak** [comment]
@joshuawilson we'll merge https://github.com/fabric8io/fabric8-test/pull/1221 soon but checks for this PR will be still broken because of https://github.com/openshiftio/openshift.io/issues/4670

**Comment by ljelinkova** [comment]
@joshuawilson Please do not merge this PR yet. We've realized that https://github.com/fabric8io/fabric8-test/pull/1221 is not sufficient. It deletes all tests regarding deployments but that also means that the e2e tests would not test if the application is successfully deployed on stage and prod. We need to add that test first and then delete the old ones.

**Comment by ppitonak** [comment]
[e2e-test-released]  [e2e-test-beta]

**Comment by ppitonak** [comment]
@joshuawilson feel free to merge when convenient

**Comment by alien-ike** [comment]
Hey @joshuawilson! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by joshuawilson** [comment]
Look you dumb bot, I'm am the admin and there are test updates. You should be green.

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
