### PR TITLE
fix(wizard): set height variation for overflow

### PR DESCRIPTION
**Pull request by mindreeper2420**
set a new height variation on a higher parent element to account/fix the overflow issues

fixes https://github.com/openshiftio/openshift.io/issues/1155

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2297-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2297-fabric8-ui.badger.fabric8.io

**Comment by corinnekrych** [comment]
@mindreeper2420 @joshuawilson 
* on macOS (both sierra / high sierra)  with Chrome Version 62.0.3202.94 (Official Build) (64-bit) Your PR on left / PROD on right
macos_sierra_chome_62-0-3202-94-64bits

* fedora 25 with chromium 58-0-3029-110-64bits
Your PR on left / PROD on right
fedora25_chomium_58-0-3029-110-64bits

* ubuntu trustry with Chrome Version 62.0.3202.94 (Official Build) (64-bit) 
Your PR on left / PROD on right
ubutu-trusty-chrome_62-0-3202-94-64bits

I think the end result is better without the PR... But @joshuawilson could you send the exact spec of your environment: OS version + chrome version

**Comment by mindreeper2420** [comment]
@corinnekrych just shrink the vertical aspect of the screen until part of the wizard is hidden (do not shrink the diagonal or horizontal). That will replicate what Joshua and I were able to see.

I've updated the PR to include the missing overflow action. Now, when you shrink the screen to a small size (and the cards stack), it will require a scroll.

screen shot 2017-12-07 at 8 37 42 am

**Comment by corinnekrych** [comment]
[test]

**Comment by corinnekrych** [comment]
@mindreeper2420 much better on macOS side with the overflow on my 3 environments it's ok
@joshuawilson could you confirm it's ok on your side? Fedora26 + latest chrome

**Comment by corinnekrych** [comment]
@joshuawilson @mindreeper2420 Eventually i manage to reproduce it after Josh tell me not to be in mobile breakpoint
I confirm the fix work great on both mobile and desktop small height.
https://www.dropbox.com/s/5io3bz4f8y35ozz/Screenshot%202017-12-07%2015.49.52.png?dl=0

**Pull request merged**
