### PR TITLE
fix(unittests): checks the copyright info in the about dlg

### PR DESCRIPTION
**Pull request by sathishvj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2012-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2012-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2012-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2012-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2012-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2012-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@sathishvj fabric8/fabric8-ui:SNAPSHOT-PR-2012-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2012-fabric8-ui.badger.fabric8.io

**Pull request merged**
