### PR TITLE
fix(deployments): do not display fractional bytes

### PR DESCRIPTION
**Pull request by andrewazores**
fixes https://github.com/openshiftio/openshift.io/issues/2204

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2540-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2540-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2540-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2540-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
please rebase

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2540-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2540-fabric8-ui.badger.fabric8.io

**Pull request merged**
