### PR TITLE
Fix typo in "push.registry.devshift.net" commit and use env var for tag length

### PR DESCRIPTION
**Pull request by vpavlin**

### CODE REVIEW

**Comment by vpavlin** [comment]
[test]

**Comment by vpavlin** [comment]
[test]

**Comment by fabric8cd** [comment]
@vpavlin fabric8/fabric8-ui:SNAPSHOT-PR-1863-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vpavlin fabric8/fabric8-ui:SNAPSHOT-PR-1863-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vpavlin fabric8/fabric8-ui:SNAPSHOT-PR-1863-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-ui.badger.fabric8.io

**Pull request merged**
