### PR TITLE
fix(cors): remove `api` subdomain from wit api url

### PR DESCRIPTION
**Pull request by christianvogt**
In today's platform meeting, @aslakknutsen requested we change API calls from `https://api.openshift.io/api/` to `https://openshift.io/api/`.

Tested dev with prod and prod-preview environments.

- updated environment scripts
- updated webpack dev fallback
- removed wit prefix from `api-locator.service.ts`

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @christianvogt for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by christianvogt** [comment]
@jiekang Joshua and I looked for a deployment config that has the wit url and couldn't find one. I think the locator service constructs the urls for prod.

**Comment by jiekang** [comment]
@christianvogt Okay, sounds good. A quick search shows the following two also might need changes. What do you think?
https://github.com/fabric8-ui/fabric8-planner/blob/15bcc7f5ae9e6551e37c46120bd8319d9f21152e/cico_test_prod.sh
https://github.com/fabric8io/fabric8-pipeline-library/blob/b1478e95f0ce49d032007c026b2b2b5696c84c7e/vars/deployOpenShiftSnapshot.groovy

It looks like those are the only two that have recent commits. There are a lot of repositories that haven't had commits since 2017

**Comment by christianvogt** [comment]
Thanks @jiekang. I knew about the planner one but not the other.

**Comment by aslakknutsen** [comment]
>  A quick search shows the following two also might need changes. What do you think?

Just to note, both URLs will still work. It's just a way to avoid in-flight checks in prod. The UI would need to be hosted from 'openshift.io' to work, which is not the cause on PR deployments so technically it doesn't matter which URL it use.

**Pull request merged**
