### PR TITLE
fix(profile): updae profile should not send registrationcompleted in …

### PR DESCRIPTION
**Pull request by corinnekrych**
…request
Fixes https://github.com/openshiftio/openshift.io/issues/2691

### CODE REVIEW

**Comment by joshuawilson** [comment]
@corinnekrych you know this code better then I do, do you think there is a test that would have caught it?

**Comment by joshuawilson** [comment]
@dgutride can you please review too?

**Comment by sbose78** [comment]
@corinnekrych , The ideal fix is to send only the `contextInformation` attribute. Is there a simple way to do that ? This solution to remove is stop-gap in nature.

**Comment by corinnekrych** [comment]
@sbose78 I also need featureLevel, contextInformation is not enough

**Comment by sbose78** [comment]
Sure. Apologies - I wanted to imply `featureLevel`

**Comment by corinnekrych** [comment]
Agreed @rohitkrai03 @sbose78 I've added a task here:https://github.com/openshiftio/openshift.io/issues/2625#issuecomment-375262177
Let me rebase and merge so that prod-preview can work with user consent update

**Comment by corinnekrych** [comment]
[test]

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2649-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2649-fabric8-ui.badger.fabric8.io

**Pull request merged**
