### PR TITLE
fix(deployments): unsubscribe deployments service subscriptions

### PR DESCRIPTION
**Pull request by jiekang**
Addresses https://github.com/openshiftio/openshift.io/issues/2020

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
Ah, I think this is due to injector hierarchy. We provide the DeploymentsService at the Deployments module level, which means that the service will be initialized once and then live forever. If we change this to a Component-level (DeploymentsComponent - the root of the feature/tab) provide, then the service will be brought up and torn down along with the component.

https://angular.io/guide/dependency-injection#ngmodule-or-component

tl:dr - this patch also needs the following added to make a difference:

`
diff --git a/src/app/space/create/deployments/deployments.component.ts b/src/app/space/create/deployments/deployments.component.ts
index b0abf83f..52e050f8 100644
--- a/src/app/space/create/deployments/deployments.component.ts
+++ b/src/app/space/create/deployments/deployments.component.ts
@@ -10,7 +10,8 @@ import { DeploymentsService } from './services/deployments.service';
   encapsulation: ViewEncapsulation.None,
   selector: 'alm-apps',
   templateUrl: 'deployments.component.html',
-  styleUrls: ['./deployments.component.less']
+  styleUrls: ['./deployments.component.less'],
+  providers: [DeploymentsService]
 })
 export class DeploymentsComponent implements OnDestroy, OnInit {
 
diff --git a/src/app/space/create/deployments/deployments.module.ts b/src/app/space/create/deployments/deployments.module.ts
index bd1d69ee..04984235 100644
--- a/src/app/space/create/deployments/deployments.module.ts
+++ b/src/app/space/create/deployments/deployments.module.ts
@@ -53,8 +53,7 @@ import { DeploymentsService } from './services/deployments.service';
     UtilizationBarComponent
   ],
   providers: [
-    BsDropdownConfig,
-    DeploymentsService
+    BsDropdownConfig
   ]
 })
 export class DeploymentsModule {

`

This breaks some tests due to the provide scope change.

**Comment by andrewazores** [comment]
Re. last comment - see https://github.com/openshiftio/openshift.io/issues/2104

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-12 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
please rebase

**Comment by fabric8cd** [comment]
@jiekang fabric8/fabric8-ui:SNAPSHOT-PR-2439-13 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2439-fabric8-ui.badger.fabric8.io

**Pull request merged**
