### PR TITLE
fix(404): Update 404 page to match new designs

### PR DESCRIPTION
**Pull request by mindreeper2420**
**Updated 404 page:**
screen shot 2018-03-12 at 2 38 27 pm

### CODE REVIEW

**Comment by mindreeper2420** [comment]
related to https://github.com/fabric8-ui/fabric8-ux/issues/894

**Comment by joshuawilson** [comment]
@mindreeper2420 looks like you have other images to add. Why only add the one?

**Comment by mindreeper2420** [comment]
@joshuawilson - there is only one image for the 404...not sure what else you are referencing?

**Comment by joshuawilson** [comment]
Ah, right. I was thinking of all the pages in the design.

**Comment by mindreeper2420** [comment]
Oh yeah - those will be handled separately :-)

**Comment by mindreeper2420** [comment]
Closing this, per request, as we find a different illustration.

**Pull request closed without merging**
