### PR TITLE
fix(wizard): Fix wizard redirect when in space

### PR DESCRIPTION
**Pull request by dgutride**
https://github.com/openshiftio/openshift.io/issues/1070

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2076-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-ui.badger.fabric8.io

**Comment by corinnekrych** [comment]
@dgutride could we hold on before merging that one I think we fix similar issue in here: https://github.com/fabric8-ui/fabric8-ui/pull/2077 but in a different way.

**Comment by dgutride** [comment]
Replaced with @corinnekrych's work - abandoning

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2076-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
