### PR TITLE
chore(runtime+scripts):planner dead code removal

### PR DESCRIPTION
**Pull request by abhinandan13jan**
removing runtime from planner codebase
ref: https://openshift.io/openshiftio/Openshift_io/plan/detail/1345

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @abhinandan13jan for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by sahil143** [comment]
> removing runtime from planner codebase
ref: #1345 task

@abhinandan13jan referenced issue is not related to this PR

**Comment by abhinandan13jan** [comment]
@sahil Can you please review

**Pull request merged**
