### PR TITLE
refactor(deployments): reorder params to be space, env, app

### PR DESCRIPTION
**Pull request by c-koehler**
fixes #2586

### CODE REVIEW

**Comment by c-koehler** [comment]
I checked this by Find Usages, and also did a regex search for something like `space.*env.*app.*` to find any missed conversions.

NOTE: Should not be merged until after I post another message, as I have to test something when I get in Monday morning and get OSIO working properly. There can still be a code review I assume.

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2643-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2643-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
`deployments.service.spec.ts`:
`      svc.scalePods('foo-spaceId', 'vertx-hello', 'stage', 2)`
- doesn't affect test result but should still follow correct order

This is the only spot I found where the params are still out of order. I found this by looking over all of the public functions in `DeploymentsService` and grepping for all of the functions' names that have both environment and application in their params list.

I think we can use this PR as an opportunity to improve the quality of our unit tests as well, which will also help us catch any more of these problems that we may have missed and provide a good regression catcher in the future. Any instances of DeploymentsService test mocks that do ex. `expect(mockSvc.deleteDeployment).toHaveBeenCalled()` should include the parameters that the mock function member should have been called with. So the previous should become `expect(mockSvc.deleteDeployment).toHaveBeenCalledWith('space', 'env', 'app')` for example. If we apply this to all of the unit tests separately in another commit on top of this one we can be sure that we haven't missed any more call sites and that we're better protected against possibly making this kind of mistake in the future.

**Comment by c-koehler** [comment]
@andrewazores I went through each function in the deployments service and searched for the usages to see where it's consumed, over all our files most of them were covered (which is good!) and that means there was i think 7 or 8 places where new tests had to have been added. Our tests look pretty robust as far as I can tell even without the changes added, so that is great overall.

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2643-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2643-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
Latest patch looks good, but I'm unable to manually test it currently due to https://github.com/openshiftio/openshift.io/issues/2710 . I'll hold off on approving this until I can give it a quick smoke test.

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2643-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2643-fabric8-ui.badger.fabric8.io

**Comment by c-koehler** [comment]
@andrewazores Rebased and fixed merge errors. The only line from your commit that I needed to update when I rebased was this line: https://github.com/fabric8-ui/fabric8-ui/pull/2643/files#diff-094a28eb093d18ac23e3c3ba0b5deca9R552

and FWIW, that was caught due to the tests showing the improper ordering -- the line above during the merging escaped me somehow when resolving merge conflicts, but the tests caught it, so it looks like a pretty nice upgrade that is paying off already!

**Comment by fabric8cd** [comment]
@c-koehler fabric8/fabric8-ui:SNAPSHOT-PR-2643-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2643-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
@c-koehler nice, glad to hear it!

**Pull request merged**
