### PR TITLE
Move to talamer namespace for scripts and widgets package

### PR DESCRIPTION
**Pull request by rohitkrai03**

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @rohitkrai03 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by christianvogt** [comment]
Remove the changes to `api.config.ts` from this PR as I've made a fix to the webpack config in another PR for this issue.

**Comment by rohitkrai03** [comment]
@christianvogt Done.

**Pull request merged**
