### PR TITLE
fix(pipelines): do not emit error if 401 recieved when not logged in

### PR DESCRIPTION
**Pull request by jiekang**
This addresses the error notification that appears if you are not logged in and visit a space. It will not appear if you are not logged in. This makes an assumption that 'logged in' means there is an auth token in local storage (looking at how authentication service actually works). I think this is reasonable. If the auth token is invalid, it will still notify, which is nice.

This fixes https://github.com/openshiftio/openshift.io/issues/3347

Interestingly the auth token service implementation returns the value in local storage or the empty string so in theory it will never be null. I think there's a few http services that do a null check on the getToken function; they should also probably not add the header if the return value is an empty string. Alternatively, the auth service should return null as the local storage could contain a key with an empty value.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jiekang for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by jiekang** [comment]
Oh I should add tests. Thanks test-keeper :)

**Comment by jiekang** [comment]
I have added tests, for what it's worth.

**Comment by andrewazores** [comment]
The verb can be changed from "fix" to "test" on the second commit.

Seems fine otherwise. There are probably other places where we would need to make a similar change to avoid the same bug report symptoms from different views. Not sure at this point how we would go about generalizing this solution - I guess we would need to look to the application-wide notification system for that.

**Pull request merged**
