### PR TITLE
fix(tests): update tests to run on MacOS

### PR DESCRIPTION
**Pull request by mindreeper2420**
Update the tests to run on MacOS, in addition to original platforms

This is related to https://github.com/fabric8io/fabric8-test/commit/2d509b9fecc1ced0167839dcd1b3b16ffdac0af9

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1998-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1998-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1998-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1998-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1998-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1998-fabric8-ui.badger.fabric8.io

**Pull request merged**
