### PR TITLE
Remove depricated and now unused app-creation functionality

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses [issue 3629](https://github.com/openshiftio/openshift.io/issues/3629) [0], which removes the unused code from the legacy app launcher and add-codebases action. As stated in the issue, the goal is to have the new launcher as the sole launcher, and not be hidden behind any feature flags. This should additionally clear up other issues such as [issue 3489](url). 

I've kept my series of commits for the sake of review, so each step can be looked at individually. I started with the old forge wizard and individually removed each of its submodules. Lastly, I removed the unused add-codebases slider which used to be present on the `/create` page, but has since been updated to use the new launcher as well.

[0] https://github.com/openshiftio/openshift.io/issues/3629
[1] https://github.com/openshiftio/openshift.io/issues/3489

### CODE REVIEW

**Comment by jyasveer** [comment]
@aptmac can you please resolve the merge conflicts here ?

**Comment by joshuawilson** [comment]
@aptmac when you write the commit, please use the syntax in the README. Specifically, use a present tense verb to start the message. You go back and forth between `remove` and `removed`.

**Comment by jiekang** [comment]
s/depricate/deprecate

**Comment by aptmac** [comment]
> s/depricate/deprecate

Thanks, I'm spoiled too much by spell check these days ..

**Comment by edewit** [comment]
@aptmac The error with the Broadcaster has been resolved in `ngx-forge@0.2.25`

**Comment by jyasveer** [comment]
@aptmac i built this PR and I am getting these errors here
https://paste.fedoraproject.org/paste/Oiq2nBVGKZRarUzmvwf7ww

**Comment by aptmac** [comment]
@jyasveer I had forgotten to remove a couple instances of the codebases-add module, sorry about that. It should be okay now.

**Comment by fabric8cd** [comment]
@aptmac fabric8/fabric8-ui:SNAPSHOT-PR-2980-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2980-fabric8-ui.badger.fabric8.io

**Comment by jyasveer** [comment]
@aptmac the PR is building now :-). i am still reviewing though

**Pull request merged**
