### PR TITLE
fix(codebase): context no longer contains 'forge'

### PR DESCRIPTION
**Pull request by gastaldi**
This reverts commit 649ee853fdca2cd8513650141a7b8021f96f1066.

### CODE REVIEW

**Comment by gastaldi** [comment]
This is part of the https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/994 issue and should be merged when we reach the "Validate" step in the issue

**Comment by bartoszmajsak** [comment]
[test]

**Comment by joshuawilson** [comment]
you might just want to submit a new PR with the fix in it. It would be cleaner.

**Comment by gastaldi** [comment]
@edewit I need your +1 in this PR

**Comment by joshuawilson** [comment]
you guys need to update your commits, they don't use the right syntax. 
https://github.com/fabric8-ui/fabric8-ui#continuous-delivery--semantic-releases

**Comment by joshuawilson** [comment]
[test]

**Comment by gastaldi** [comment]
Closing messy PR

**Pull request closed without merging**
