### PR TITLE
fix linting issues

### PR DESCRIPTION
**Pull request by joshuawilson**
Apply some of the linting rules and fix them. Only rules that pass are not on.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-2367-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2367-fabric8-ui.badger.fabric8.io

**Comment by corinnekrych** [comment]
LGTM

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-2367-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2367-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-2367-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2367-fabric8-ui.badger.fabric8.io

**Pull request merged**
