### PR TITLE
fix(launcher): upgrade ngx-launcher to 3.4.23

### PR DESCRIPTION
**Pull request by vikram-raj**
fix - https://github.com/openshiftio/openshift.io/issues/4569
fix - https://github.com/openshiftio/openshift.io/issues/4539

### CODE REVIEW

**Comment by christianvogt** [comment]
@vikram-raj  could you please add unit tests for the calls to `resetState`

**Comment by vikram-raj** [comment]
@christianvogt Sure.

**Comment by ppitonak** [comment]
[e2e-test-beta]

**Comment by vikram-raj** [comment]
[test]

**Comment by christianvogt** [comment]
@vikram-raj build is failing

**Comment by ppitonak** [comment]
Could we update directly to 3.4.22?

**Comment by vikram-raj** [comment]
>Could we update directly to 3.4.22?

Yes, we can directly upgrade to 3.4.22.

**Comment by vikram-raj** [comment]
I moved the test to ```ngx-launcher``` https://github.com/fabric8-launcher/ngx-launcher/pull/570. As I am not able to handle the other component of ```ngx-launcher``` here. That was the reason of failing the build.

**Comment by vikram-raj** [comment]
@ppitonak I upgrade ```ngx-launcher``` to version ```3.4.23```. In this version there is change in git provider component. That is while fetching the user data we show a loader to user.

**Pull request merged**
