### PR TITLE
fix(telemetry): Add telemetry for App Launcher

### PR DESCRIPTION
**Pull request by jyasveer**
User Story :- https://github.com/openshiftio/openshift.io/issues/3241

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @jyasveer for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-3000-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-3000-fabric8-ui.badger.fabric8.io

**Comment by jyasveer** [comment]
I am waiting on this PR https://github.com/fabric8-ui/ngx-base/pull/34

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-3000-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-3000-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@davidfestal would you mind looking at this?
@rahulm0101 you should take a look too.

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-3000-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-3000-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-3000-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-3000-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-3000-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-3000-fabric8-ui.badger.fabric8.io

**Comment by jyasveer** [comment]
> That seems good to me by looking into the code, but I don't see any related events in either test.openshift.io or prod.openshift.io woopra domains.

Is there any way to look at the resulting woopra events ? I assume you are using a dedicated woopra domain for development: maybe you could provide me access to give a look ?

@davidfestal i am not sure about how to add events in the woopra domain ? can you please help me in doing so. Thanks

**Comment by jyasveer** [comment]
Related to https://github.com/fabric8-launcher/ngx-launcher/pull/279

**Comment by jyasveer** [comment]
@davidfestal @rahulm0101 
can you please approve this PR if you find okay

**Comment by davidfestal** [comment]
@jyasveer I don't know if you tested your PR with pointing to the test woopra instance, but I don't see any events related to your PR in the `test.openshift.io` woopra instance currently...

**Comment by jyasveer** [comment]
> @jyasveer I don't know if you tested your PR with pointing to the test woopra instance, but I don't see any events related to your PR in the test.openshift.io woopra instance currently...

yes @davidfestal i have tried earlier to test my PR with the test woopra instance. i have used the test source key to raise events to segment . Please help me to verify the events in test woopra system. Thanks

**Comment by jyasveer** [comment]
@davidfestal @rahulm0101
Can you please review and approve this PR if you find okay ?
Thanks

**Comment by davidfestal** [comment]
> Based on our yesterday's call, we saw that events are getting registered in the woopra. So if you find this PR okay, can you please review and approve ?

Don't you plan to fix the cases when event properties comes like an unreadable object (`[object Object]`) first ? Or do you prefer doing that in a next PR ?

**Comment by jyasveer** [comment]
That i have addressed in this PR. you could see a version change in the package.json for ngx-forge in this PR

**Comment by davidfestal** [comment]
> That i have addressed in this PR. you could see a version change in the package.json for ngx-forge in this PR

Ah, great ! OK for me to merge then :+1:

**Comment by jyasveer** [comment]
@davidfestal Many thanks :-)

**Comment by jyasveer** [comment]
@joshuawilson can you please merge this PR now ? thanks

**Pull request merged**
