### PR TITLE
fix(loggedinuser): start using loggedInUser from static var

### PR DESCRIPTION
**Pull request by dgutride**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2482-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2482-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2482-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2482-fabric8-ui.badger.fabric8.io

**Pull request merged**
