### PR TITLE
feat(collaborators): add heading to collaborators page and changes for username

### PR DESCRIPTION
**Pull request by rohitkrai03**
Planner WI - https://openshift.io/openshiftio/Openshift_io/plan/detail/781

- Add heading for collaborators page list.
- Changes design for usernames in the list.

Screenshots - 
screenshot 2018-10-23 at 10 54 24 pm

cc: @fabric8-ui/uxd

### CODE REVIEW

**Comment by joshuawilson** [comment]
@fabric8-ui/uxd @fabric8-ui/docs @rkratky please review.

**Comment by muruGanesan** [comment]
@rohitkrai03 , @joshuawilson ,

There is a minor change in the heading: (please correct it)
image

**Comment by rohitkrai03** [comment]
@muruGaneshan I had updated the screenshot yesterday night only. Where did you tested it?

**Comment by christianvogt** [comment]
@rohitkrai03 I think @muruGanesan was only referring to a change in the design after @joshuawilson made a comment in the invision. You seem to have already implemented the latest changes.

**Comment by muruGanesan** [comment]
> @muruGanesan I had updated the screenshot yesterday night only. Where did you tested it?

@rohitkrai03, I took the screen from the GitHub notification. But it doesn't matter now. Current implementation looks perfect. Thanks

**Pull request merged**
