### PR TITLE
fix(launcher): updates default values for artifact, group_id, version

### PR DESCRIPTION
**Pull request by invincibleJai**
### Updates defalut values in service for new launcher flow

- updates default values for artifact, group_id, version

fixes below issues
- https://github.com/openshiftio/openshift.io/issues/2833
- https://github.com/openshiftio/openshift.io/issues/2837

### CODE REVIEW

**Comment by fabric8cd** [comment]
@invincibleJai fabric8/fabric8-ui:SNAPSHOT-PR-2681-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2681-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Please add a link the issue for tracking this change.

**Comment by invincibleJai** [comment]
fixes below issues
- https://github.com/openshiftio/openshift.io/issues/2833
- https://github.com/openshiftio/openshift.io/issues/2837

**Comment by fabric8cd** [comment]
@invincibleJai fabric8/fabric8-ui:SNAPSHOT-PR-2681-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2681-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@invincibleJai fabric8/fabric8-ui:SNAPSHOT-PR-2681-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2681-fabric8-ui.badger.fabric8.io

**Pull request merged**
