### PR TITLE
feat(deployments): add menu items to mirror design mockup

### PR DESCRIPTION
**Pull request by andrewazores**

### CODE REVIEW

**Comment by andrewazores** [comment]
That test failure doesn't look like it'd be caused by this change :/

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2257-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2257-fabric8-ui.badger.fabric8.io

**Comment by mindreeper2420** [comment]
Can you link the original issue or design that this is based off of? Thanks!

**Comment by andrewazores** [comment]
https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764295

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2257-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2257-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2257-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2257-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2257-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2257-fabric8-ui.badger.fabric8.io

**Pull request merged**
