### PR TITLE
Pact tests

### PR DESCRIPTION
**Pull request by edewit**
fixed the pact tests @corinnekrych

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Great stuff @edewit - on the backend side, which we are working on we are going to reuse the same pacts and thus provide a way to store it outside of this project. For the moment

**Comment by bartoszmajsak** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by bartoszmajsak** [comment]
@edewit @joshua I don't think we should merge it just yet?

**Comment by joshuawilson** [comment]
what is the status on this?

**Comment by corinnekrych** [comment]
@joshuawilson @edewit @bartoszmajsak I think we can close this one I know Erik has started working on it on a new branch

**Comment by bartoszmajsak** [comment]
This is still WIP

**Comment by corinnekrych** [comment]
oops my bad I meant to close this one: https://github.com/fabric8-ui/fabric8-ui/pull/1979

**Comment by joshuawilson** [comment]
@bartoszmajsak Is this PR still valid? Why are we waiting on it?

@edewit Can you please rebase it.

**Comment by edewit** [comment]
@joshuawilson this was a test for the legacy launcher we'll need to update this for the new one IMO

**Pull request closed without merging**
