### PR TITLE
fix(stack-report-btn): fixes stack report button not appearing in pip…

### PR DESCRIPTION
**Pull request by invincibleJai**
- fixes stack report button not appearing in pipelines view wrt recent change in stage name

Tracks: https://github.com/openshiftio/openshift.io/issues/4405

### CODE REVIEW

**Comment by joshuawilson** [comment]
What configuration gets a build with a report? I just tried Spring and REST and got no report.

**Comment by invincibleJai** [comment]
@joshuawilson let me try with spring and rest. Ideally if we try this PR and build goes through successful, Stack report should show up in dashboard as well as stack report link should appear in pipelines.

Stack report should work fine if annotations from build are proper as in https://github.com/openshiftio/openshift.io/issues/3744#issuecomment-395299143

**Comment by invincibleJai** [comment]
I tried spring and rest, it works for me.

screen shot 2018-10-11 at 8 36 31 am

**Comment by joshuawilson** [comment]
I ran your branch locally and I don't see the report link.

**Comment by invincibleJai** [comment]
@joshuawilson oh, can you pls share jenkins log for that build.

**Comment by joshuawilson** [comment]
I can see it now.

**Pull request merged**
