### PR TITLE
Format My Spaces list as table

### PR DESCRIPTION
**Pull request by andrewazores**
related to https://openshift.io/openshiftio/Openshift_io/plan/detail/845

Current state of restyling:

image

Collaborators and Work Items counts are currently hardcoded to 0.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @andrewazores for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by andrewazores** [comment]
Will rebase atop of https://github.com/fabric8-ui/fabric8-ui/pull/3381 to share service code.

Work items count is now hardcoded to "-", which is also the initial/loading state for the collaborators count. The collaborators count is properly queried and updated.

**Comment by andrewazores** [comment]
Work Items count is now actually queried and updated as well. After I add tests this will be ready for rebase atop Alex's #3381 feature branch.

**Comment by andrewazores** [comment]
Ready for rebase.

**Comment by andrewazores** [comment]
Here's a quick demo that (briefly) shows the initial loading state as well. Each item starts with "-" for collaborator and workitem counts.

https://youtu.be/jU-J6jP9Gww

**Comment by aptmac** [comment]
Overall this looks good to me. The only concern I have about this right now is similar to your comment [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3382#pullrequestreview-167079918) regarding cached values. I "own" 23 spaces currently, so every time the chart initializes "My Spaces" I'm seeing 46 requests (23 for collaborator info, 23 for work item info). I realize that _most_ users may not encounter this type of traffic, because I only made this many spaces for testing purposes. 

[0] https://github.com/fabric8-ui/fabric8-ui/pull/3382#pullrequestreview-167079918

**Comment by christianvogt** [comment]
@aptmac this is one of the reasons we want to support graphql. Otherwise we need to create specialized services tailored to these use cases thus increasing the number of endpoints as the complexity of the UI grows.

We support it but i *think* json api allows us to add qualified `includes` values: `/space/{spaceID}?includes=collaborators.totalCount,workitems.totalCount`
Even this isn't very good because what if we wanted to filter the workitems and count only those that are opened.

**Comment by joshuawilson** [comment]
@fabric8-ui/uxd @fabric8-ui/docs @rkratky please review.

**Comment by joshuawilson** [comment]
@andrewazores please submit this as a new PR since we had to revert from before it.

**Comment by Preeticp** [comment]
Docs have been updated for these changes through: https://github.com/fabric8io/fabric8-online-docs/pull/450

**Comment by Preeticp** [comment]
@joshuawilson please note: Changes that are on prod will be pushed out to prod docs. Those changes which are only on prod-preview, such as the 'Find a space to join' are documented but commented out, they will be pushed to prod once these changes are in prod.

Also, while testing the feature, I see that the the Add Pin option in the kebab menu to the right of a space, does not pin the space nor move it to the top of my list. Is this still a WIP?

**Comment by joshuawilson** [comment]
It looks like the "pin" feature doesn't work.

**Pull request merged**
