### PR TITLE
feat(deployments): retrieve list of apps and environments from WIT en…

### PR DESCRIPTION
**Pull request by andrewazores**
…dpoint

related to https://github.com/openshiftio/openshift.io/issues/1370

This is the initial commit for integration the Deployments area with the backend in WIT (as of https://github.com/fabric8-services/fabric8-wit/pull/1798 ). There are more commits to come in separate PRs to replace the other mock implementations within DeploymentsService with real HTTP requests.

In this commit, the DeploymentsService#isDeployedInEnvironment implementation is stubbed to always return 'true' - I haven't come up with a good way to implement this with the current state of the API responses from the backend. It'll be addressed with a follow-up commit so the rest of this work is not blocked, since the solution may need to involve backend support.

### CODE REVIEW

**Comment by andrewazores** [comment]
Also - this PR should probably not be merged until after the WIT PR (https://github.com/fabric8-services/fabric8-wit/pull/1798) has bubbled up to at least prod-preview as well.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2399-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2399-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
@andrewazores Regarding the implementation for `isDeployedInEnvironment`, isn't this information provided by `/apps/spaces/{spaceId}`?

E.g. from
```
{"data":{"applications":[{"name":"osio-prod","pipeline":[{"name":"stage","pods":{"running":1,"starting":0,"stopping":0,"total":1},"version":"1.0.1"}]}]}}
```

we can tell the application osio-prod is deployed in stage and nowhere else.

**Comment by andrewazores** [comment]
@jiekang ah, I had it in my head that the response there would still include environments (pipeline stages) even when not deployed, but that may have been totally incorrect. I'll take a closer look with that follow-up PR, but it does seem like what you say would work. Thanks for the lead.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2399-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2399-fabric8-ui.badger.fabric8.io

**Pull request merged**
