### PR TITLE
fix(version): update ngx-forge to 0.0.72

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by invincibleJai** [comment]
@joshuawilson this PR already took the changes https://github.com/fabric8-ui/fabric8-ui/pull/2717, this can be ignored

CC @jyasveer

**Comment by joshuawilson** [comment]
This PR removes the `-development`. Since you updated the `fabric8-npm-dependencies`.

Maybe we should keep this.

**Comment by jyasveer** [comment]
This PR is only for testing purpose @joshuawilson.

**Comment by joshuawilson** [comment]
You didn't submit this PR. It came after I merged your PR to add this to `fabric8-npm-dependencies`.

It is not a test PR.

**Pull request closed without merging**
