### PR TITLE
Import.wizard.static.endpoint.call

### PR DESCRIPTION
**Pull request by corinnekrych**
WIP - do not merge

### CODE REVIEW

**Comment by joshuawilson** [comment]
@kbsingh this one is failing on time out too.

**Comment by kbsingh** [comment]
@joshuawilson @corinnekrych we can extend that, let me do it now and double it.

**Comment by kbsingh** [comment]
https://github.com/almighty/almighty-jobs/pull/302 should bring the timeout to 50m

**Comment by corinnekrych** [comment]
close this one in favor of the rebased PR https://github.com/fabric8-ui/fabric8-ui/pull/2077

**Pull request closed without merging**
