### PR TITLE
fix(feature-banner): make choice about experimental features persistent

### PR DESCRIPTION
**Pull request by dlabrecq**
Makes choice about experimental features persistent

Fixes: https://github.com/openshiftio/openshift.io/issues/1557

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2414-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2414-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
please add a test against the service

**Comment by dlabrecq** [comment]
Added a test for the service

**Comment by corinnekrych** [comment]
@dlabrecq Looking at the code I've just raised one question on the issue: https://github.com/openshiftio/openshift.io/issues/1557#issuecomment-363023651 otherwise the code looks ok to me. I'm just waiting on the answer.

**Comment by joshuawilson** [comment]
@dlabrecq please rebase
@corinnekrych do you approve?

**Comment by corinnekrych** [comment]
+1 for me

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2414-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2414-fabric8-ui.badger.fabric8.io

**Pull request merged**
