### PR TITLE
feat(feature-flag): remove restricttedattribute for f8-feature-toggle…

### PR DESCRIPTION
**Pull request by corinnekrych**
… component
Fixes https://github.com/openshiftio/openshift.io/issues/3048 
See documentation: https://github.com/fabric8-ui/fabric8-ui/wiki/fabric8-toggles#enable-by-emails

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @corinnekrych for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by mindreeper2420** [comment]
@dlabrecq this will affect your current work with the Application Widget on the new Space Dashboard.

**Comment by alien-ike** [comment]
Hey @corinnekrych! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer, but not pull request creator for this command to take an effect.

**Comment by corinnekrych** [comment]
[test]

**Pull request merged**
