### PR TITLE
fix(styles): Updated analytic widget styles to support the new design

### PR DESCRIPTION
**Pull request by jyasveer**

### CODE REVIEW

**Comment by joshuawilson** [comment]
@mindreeper2420 please review

**Comment by joshuawilson** [comment]
Can you please explain what this is supposed to do? A before and after screen shot are usually given for a style change. 
Is there an issue tracking this?

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-2515-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2515-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
