### PR TITLE
CSS typo

### PR DESCRIPTION
**Pull request by dlabrecq**
Fixed typo with animation CSS

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-1763-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1763-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-1763-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1763-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@dlabrecq this fix needs to be rebased, it still has the previous commit in it.

**Comment by dlabrecq** [comment]
Thanks! I've rebased.

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-1763-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1763-fabric8-ui.badger.fabric8.io

**Pull request merged**
