### PR TITLE
fix(profile): remove path collision with "View all spaces"

### PR DESCRIPTION
**Pull request by andrewazores**
fixes https://github.com/openshiftio/openshift.io/issues/3872

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @andrewazores for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by aptmac** [comment]
Functionality wise this fix looks good, but I just want to get approval regarding what the URL should look like because we have some very particular routings in OSIO (e.g., spaces vs. _spaces)

@fabric8-ui/uxd @mindreeper2420 what should the URL look like when routing to a users profile spaces/work items page? Can we use `/{username}/_profile/{spaces || workitems}`?

**Comment by joshuawilson** [comment]
@catrobson can you please have someone look at this

**Pull request merged**
