### PR TITLE
cleanup(email-verification): remove unused component for email verification

### PR DESCRIPTION
**Pull request by rohitkrai03**
Fixes https://github.com/fabric8-services/fabric8-auth/issues/658
- Removes unused component and module for email verification
- After https://github.com/fabric8-ui/fabric8-ui/pull/3259 we do not need this old component and module.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @rohitkrai03 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by rohitkrai03** [comment]
@joshuawilson We can merge this.

**Pull request merged**
