### PR TITLE
fix(feature-flag): Feature flag dedicated page when user-enablement i…

### PR DESCRIPTION
**Pull request by corinnekrych**
…s not allowing feature display
fixes https://github.com/openshiftio/openshift.io/issues/2554

### CODE REVIEW

**Comment by jiekang** [comment]
Looks to work for me. @corinnekrych I'd appreciate more description on either the issue or the PR for what this is doing.

Did UX ever work on designs for the feature toggle experience? I think at the start this was just prototyping but now it's quite functional. Is this something they're aware of? @joshuawilson do you know?

**Comment by corinnekrych** [comment]
@jiekang See the whole EPIC: https://github.com/openshiftio/openshift.io/issues/1165 you'll have everything linked there!
And yes UX works on it.

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2628-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2628-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
I do agree that the description could have been a bit clearer as to what this does. Since I have the back ground, I am able to follow the work but not everyone else has the time to read all the other issues to understand how this fits in.

**Pull request merged**
