### PR TITLE
fix(quickstart): wizard scrub output from forge to default github pro…

### PR DESCRIPTION
**Pull request by corinnekrych**
…ject name to space name

fixes https://github.com/fabric8-ui/fabric8-ui/issues/1910

### CODE REVIEW

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-1914-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1914-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-1914-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1914-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-1914-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1914-fabric8-ui.badger.fabric8.io

**Comment by corinnekrych** [comment]
@jstrachan with the new backend we still got the `[canMoveToNext: false` issue](https://github.com/fabric8io/fabric8-generator/issues/51), I'm clueless about that one:/
I've done a hack around it.
Please review. 
I've tested both flows import and quickstart work ok.

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-1914-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1914-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-1914-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1914-fabric8-ui.badger.fabric8.io

**Pull request merged**
