### PR TITLE
fix(launcher): updates key names for launch and import call

### PR DESCRIPTION
**Pull request by invincibleJai**
### Launcher

- updates key names for launch and import call

Associated PR : https://github.com/fabric8-launcher/launcher-backend/pull/321

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @invincibleJai for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by alien-ike** [comment]
Hey @gastaldi! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer, but not pull request creator for this command to take an effect.

**Comment by gastaldi** [comment]
[test]

**Comment by bartoszmajsak** [comment]
For the record - https://github.com/arquillian/ike-prow-plugins/issues/118

**Comment by gastaldi** [comment]
@joshuawilson can you merge this PR?

**Pull request merged**
