### PR TITLE
Fix(recent-utils): fix signature of recent-utils#compareElements

### PR DESCRIPTION
**Pull request by christianvogt**
Fixes the signature of `recent-utils#compareElements` which causes test failures in the monorepo. The abstract function should not be typed as the generic comes from the class and not should not come from the function.

This function is implemented in `spaces.service` and `context.service` as follows:
```
  compareElements(s1: Space, s2: Space): boolean {
    return s1.id === s2.id;
  }
```
```
  compareElements(c1: Context, c2: Context): boolean {
    return c1.name === c2.name;
  }
```

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @christianvogt for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by joshuawilson** [comment]
Why does the generic type need to come from the class? I can't find anything in the docs saying that.

**Comment by joshuawilson** [comment]
I don't think method is called anyplace but from within this class. The methods that are called don't use the compare feature. You might be able to remove it.

**Comment by christianvogt** [comment]
The type applied at the function level `compareElements<T>` infers the type from the assignment which is wrong because the return value is a boolean. Whereas we should be using `T` from the class itself.

**Comment by joshuawilson** [comment]
There is no unit test for this. 
I know it is an abstract class, but you should be able to mock it.

**Comment by christianvogt** [comment]
@joshuawilson well that was fun writing tests :)

**Pull request merged**
