### PR TITLE
Issue 1628

### LINKED ISSUE #1628: continues page reload loop
_From @debianmaster on June 29, 2017 18:22_

Goto:  https://openshift.io/cjonagam-io/_spaces     `replace cjonagam-io` with your yousername

and click `New` button   page goes into infinite loop of   Reload -> New -> Reload

_Copied from original issue: openshiftio/openshift.io#304_

### PR DESCRIPTION
**Pull request by kylebuch8**
fixes #1628

### CODE REVIEW

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1713-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1713-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by dgutride** [comment]
[test]

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1713-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1713-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1713-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1713-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1713-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1713-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kylebuch8 fabric8/fabric8-ui:SNAPSHOT-PR-1713-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1713-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
