### PR TITLE
fix(version): Update planner version to 0.49.0

### PR DESCRIPTION
**Pull request by nimishamukherjee**
fix(version): Update planner version to 0.49.0

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2949-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2949-fabric8-ui.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@jarifibrahim can you have a look at package-lock - lots of changes came in
I did the following:
1. unlink from the planner dist-watch
2. npm run reinstall
3. update planner to 0.49.0 in package.json
4. npm install

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2949-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2949-fabric8-ui.badger.fabric8.io

**Comment by jarifibrahim** [comment]
Closing this PR in favour of https://github.com/fabric8-ui/fabric8-ui/pull/2956

**Pull request closed without merging**
