### PR TITLE
fix(opt-in): better usage of pfng-list

### PR DESCRIPTION
**Pull request by corinnekrych**
fixes https://github.com/openshiftio/openshift.io/issues/3427

@dlabrecq now we're missing the option to have a radio-button list in the config of the component. atm the component is not compliant with https://redhat.invisionapp.com/share/KAF97RBGB#/screens/276638410 bc the radio button is "after" the border line of the expandable icon.

cc @mceledonia

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @corinnekrych for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by dlabrecq** [comment]
For single selection, the Patternfly pattern supports row selection (i.e., clicking on a row). It uses checkboxes for multiple selection. Perhaps @mceledonia intends to push that as a new pattern?

That said, I will modify patternfly-ng to support a radio button. It shouldn't take me long as I'm free at the moment.

**Comment by dlabrecq** [comment]
I've added radio button support to pfng-list. The latest package should be 3.1.5.

See: https://github.com/patternfly/patternfly-ng/pull/341

**Comment by corinnekrych** [comment]
@dlabrecq I've integrated the latest version of `pfng-list` with radio-button

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2857-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2857-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2857-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2857-fabric8-ui.badger.fabric8.io

**Pull request merged**
