### PR TITLE
fix(pipelines): avoid the missing space label

### PR DESCRIPTION
**Pull request by jstrachan**
see https://github.com/openshiftio/openshift.io/issues/383

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-1789-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1789-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@jstrachan since you fixed the issue in a different way, do you still want this change or can we close the PR?

**Comment by joshuawilson** [comment]
Fixed.

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-1789-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1789-fabric8-ui.badger.fabric8.io

**Comment by jstrachan** [comment]
@joshuawilson lets keep this PR in there just in case we ever lose track of the current space name; it shouldn't do any harm and adds handy debugging if ever something goes wrong in the space context stuff

**Pull request merged**
