### PR TITLE
fix(add-space-overlay): change Create Space and Exit button text to C…

### PR DESCRIPTION
**Pull request by vikram-raj**
…reate Empty Space and change create application icon

### CODE REVIEW

**Comment by christianvogt** [comment]
@serenamarie125 @vikram-raj was this requested by UXD?

**Comment by vikram-raj** [comment]
@christianvogt Brad wants to change the button text. He commented on the sprint review [doc](https://docs.google.com/document/d/1o0Vg0-ElZBQda99HTpajHozJz0egWYmuXe8V1PM3Uds/edit#heading=h.9rflbusd97ew).

**Comment by stacymcauliffe** [comment]
@Veethika - the "Create space and exit" button text is what we recommended. I see Brad would like it changed to "Create empty space" so I'm guessing the original copy didn't seem clear during the demo. 

We can certainly try this change. Thanks.

**Comment by muruGanesan** [comment]
> @Veethika - the "Create space and exit" button text is what we recommended. I see Brad would like it changed to "Create empty space" so I'm guessing the original copy didn't seem clear during the demo.
> 
> We can certainly try this change. Thanks.

Thank you @stacymcauliffe  and @Veethika

**Pull request merged**
