### PR TITLE
refactor(deployments): rename app-card to deployment-card

### PR DESCRIPTION
**Pull request by andrewazores**
related to openshiftio/openshift.io#1382

This does also move the component's files into a subdirectory, since there will be several more components split out and moved here in the near future.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2238-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2238-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Due to the way git tracks files, it is best to keep deletions or renaming in a separate commit. Please refactor this into 2 commits. One that changes all the file names that you want to change and another that changes content.

**Comment by andrewazores** [comment]
Okay. Does this mean that the renaming commit would also leave relative import paths broken, and the next commit would fix those as well as changing class names etc.?

**Comment by joshuawilson** [comment]
You can change the paths with the rename, just don't change anything else. Keep the commits atomic.

**Pull request closed without merging**
