### PR TITLE
[WIP] remove references to 'api.prod-preview' and change to use 'prod-preview'

### PR DESCRIPTION
**Pull request by joshuawilson**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-platform.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by aslakknutsen** [comment]
Just revert these changes, the only thing that needs to be removed is https://github.com/fabric8-ui/fabric8-ui/blob/546ade5980d4b68998377b8749318c05aae6bfbe/src/app/shared/api-locator.service.ts#L19

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-1596-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-1596-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-1596-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@joshuawilson fabric8/fabric8-ui:SNAPSHOT-PR-1596-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1596-fabric8-ui.badger.fabric8.io

**Pull request merged**
