### PR TITLE
Work Item Widget: Ensure valid links are provided for planner work items

### PR DESCRIPTION
**Pull request by dlabrecq**
This fix ensures that the work items widget, shown on the home dashboard, provides valid links to Planner work items. It also ensures the space menu options are populated correctly for recent spaces.

The issue with the space menu is that we're showing options for the user's spaces only. However, work items are shown based on recent spaces. This can leave the menu selection blank when displaying work items owned by someone else.

In order to navigate to a work item correctly, in the context of a space, we need to construct router links using the space owner -- not the logged in user. Otherwise, this widget can only show "My Work Items" for spaces owned by the user.

Unfortunately, there is no API to provide spaces based on work items owned by the user. Thus, the component displays recent spaces in order to provide some functionality. 

Fixes: https://github.com/openshiftio/openshift.io/issues/3462

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @dlabrecq for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2925-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2925-fabric8-ui.badger.fabric8.io

**Comment by dlabrecq** [comment]
Added unit tests.

**Comment by dlabrecq** [comment]
Can we merge this fix until a new API becomes available?

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2925-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2925-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-2925-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2925-fabric8-ui.badger.fabric8.io

**Pull request merged**
