### PR TITLE
fix(recent-spaces): display loading widget while recent spaces are be…

### PR DESCRIPTION
**Pull request by aptmac**
…ing retrieved

This PR was inspired by the last bullet point of a recent issue [0] regarding the initial states of components in OSIO. There are widgets that don't display the intermediate loading screen while retrieving information from the backend, and the user will see a noticeable jump from an empty state to a populated component. With regards to the home page, the only widget without a loading widget displayed is the recent spaces widget, which is the subject of this PR. (Having said that, the loading-widget on the recent-workspaces widget is displayed so quickly that if you do have workspaces to display it will actually show loading-widget -> empty-state -> loaded workspaces, but this is outside of the scope of this PR).

This PR introduces the loading-widget into the recent-spaces-widget to be displayed while waiting for the `userHasSpaces` boolean to be set. Here are some gifs below showing the before and after of this PR:

Before (notice the jump from an empty state to a loaded state)
before

After
after

[0] https://github.com/openshiftio/openshift.io/issues/4117

### CODE REVIEW

**Comment by joshuawilson** [comment]
@fabric8-ui/docs this might impact flow or screen shots, please review.
@fabric8-ui/test I don't know if this minor change in flow impacts the e2e tests, please review.

**Comment by joshuawilson** [comment]
that changes appear minor, please let me know if you find anything

**Comment by mishaone** [comment]
No impact for docs at the moment, but good to keep in mind for additional docs. Thanks, Joshua!

**Comment by ppitonak** [comment]
It indeed required a change in tests. These team notifications work as expected :+1:

**Pull request merged**
