### PR TITLE
Tweak Deployment card "Deletion" state behaviour

### PR DESCRIPTION
**Pull request by andrewazores**
See https://github.com/openshiftio/openshift.io/issues/2701

### CODE REVIEW

**Comment by jiekang** [comment]
With the proxy changes putting deployments API out of service, I can't fully test this yet. The code looks okay to me though.

**Comment by andrewazores** [comment]
@jiekang review ping now that Deployments API is back up

**Comment by jiekang** [comment]
My production Jenkins instance seems to be finnicky. Getting a build to run to test after deployment deletion succeeds with probability.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2785-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2785-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2785-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2785-fabric8-ui.badger.fabric8.io

**Pull request merged**
