### PR TITLE
refactor(feature-flag): move feature-flag.resolver from fabric8-ui to ngx-feature-flag

### PR DESCRIPTION
**Pull request by rohitkrai03**
Fixes https://github.com/openshiftio/openshift.io/issues/4116
Fixes https://github.com/fabric8-services/fabric8-auth/issues/570

- Removed redundant code of `feature-flag.resolver`
- Changed references to `FeatureFlagResolver` from local code to `ngx-feature-flag`

Note: Do not merge until https://github.com/fabric8-ui/ngx-feature-flag/pull/15 is merged and released to npm.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @rohitkrai03 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by andrewazores** [comment]
See corresponding ngx-feature-flag PR: https://github.com/fabric8-ui/ngx-feature-flag/pull/15

**Comment by joshuawilson** [comment]
I merged the FF PR, but I'm not sure if it gets automatically released. This can't be merged until that version is a part of the UI. Please change this to WIP until you get that version update in this PR.

**Comment by rohitkrai03** [comment]
@joshuawilson I think fabric8-cd is not setup for automatically releasing `ngx-feature-flag` to npm. Can someone push a manual release to npm?

**Comment by joshuawilson** [comment]
Only @corinnekrych can release as she is the only one on the npm repo. However, she did a release yesterday. You should be able to update to `0.6.0`.

**Comment by rohitkrai03** [comment]
Thanks @joshuawilson. I've updated the version number in this PR. This can be merged now.

**Pull request merged**
