### PR TITLE
[WIP] fix(quick-preview): auto-save field value when user leaves the field

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes https://github.com/openshiftio/openshift.io/issues/3951

This PR introduces the fix wherein when the user moves out of a field and clicks somewhere the field value gets automatically saved.

### CODE REVIEW

**Comment by christianvogt** [comment]
Added concerns regarding the UX and the ok / checkmark button to the parent issue.

**Comment by christianvogt** [comment]
@divyanshiGupta please look at issue #3951 and issue #4643. The real problem is data loss due to a bug in refreshing the work item details view.

**Comment by divyanshiGupta** [comment]
@christianvogt taking a look at it.

**Comment by joshuawilson** [comment]
Please rebase.

**Comment by christianvogt** [comment]
@joshuawilson do not merge this (marking WIP). Not until we have clarity on the correct approach for fixing the issue which I believe to be something else and auto save should be a separate discussion.

**Pull request closed without merging**
