### PR TITLE
chore(forge): bump version of ngx-forge

### PR DESCRIPTION
**Pull request by edewit**
The version 0.0.58-development was broken due to the
fact that is was build with the wrong version of node

### CODE REVIEW

**Comment by joshuawilson** [comment]
@gastaldi please validate and approve. I have no way of knowing what this is supposed to do. I could only check if it breaks everything else.

**Comment by fabric8cd** [comment]
@edewit fabric8/fabric8-ui:SNAPSHOT-PR-2629-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2629-fabric8-ui.badger.fabric8.io

**Comment by gastaldi** [comment]
@joshuawilson LGTM but I'd ask someone from the UI team to verify, like @dgutride

**Comment by joshuawilson** [comment]
The version was updated in #2658 to a newer version. Closing as out of date.

**Pull request closed without merging**
