### PR TITLE
fix(planner): Iteration labels not used consistently

### PR DESCRIPTION
**Pull request by Bumbilo**
- Added slash for root iteration
Issue: https://github.com/openshiftio/openshift.io/issues/2997
Issue: https://github.com/openshiftio/openshift.io/issues/4665
Issue: https://github.com/openshiftio/openshift.io/issues/4666
screen shot 2018-12-26 at 17 39 14

### CODE REVIEW

**Comment by vikram-raj** [comment]
Hey @Bumbilo, can you please add the reference to the issue that is solved by this PR.

**Comment by vikram-raj** [comment]
@Bumbilo As per UX and the [comment](https://github.com/openshiftio/openshift.io/issues/2997#issuecomment-409850979) on issue  root iteration as ```/``` should be consistance throughout the application. 
You need to do the same change for quick preview and detail page.

**Comment by nimishamukherjee** [comment]
> @Bumbilo As per UX and the [comment](https://github.com/openshiftio/openshift.io/issues/2997#issuecomment-409850979) on issue root iteration as `/` should be consistence throughout the application.
> You need to do the same change for quick preview and detail page.

@vikram-raj we can track this as a separate task.
@Bumbilo please create a separate task for this.

**Comment by vikram-raj** [comment]
@nimishamukherjee Fine for me.

**Pull request merged**
