### PR TITLE
multi pom recommendations support in analytics dashboard widget

### PR DESCRIPTION
**Pull request by jyasveer**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-1741-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1741-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-1741-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1741-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
