### PR TITLE
fix(interceptors): change interceptor sequence for redundant API calls

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This PR contains fix for redundant API calls from front end.
1. Reordered the interceptors
2. Changed the cache key generation
3. Increased the max TTL for cache.

Fixes   https://github.com/openshiftio/openshift.io/issues/4597

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @karthikjeeyar for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by christianvogt** [comment]
@karthikjeeyar remove the cache max age value as this extra time could have negative effects on the user mutating data and navigating between pages within 15 seconds. The time was kept small in order to only return cached values for components loading at the same time. We can revisit the max cache value at a later time.

**Comment by rohitkrai03** [comment]
@karthikjeeyar Take a look at how we write our commit messages and PR titles - https://github.com/fabric8-ui/fabric8-ui#continuous-delivery--semantic-releases.

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
@christianvogt please review again as a lot changed

**Comment by rohitkrai03** [comment]
@joshuawilson Latest changes looks mostly like code formatting and unrelated to the chaching issue. Looks good to me. 
@karthikjeeyar it would be better to raise separate PRs with changes that deal with different issues.

**Comment by christianvogt** [comment]
@karthikjeeyar please update the header check to this:
`JSON.stringify(req.headers.keys().map(key => ({[key]: req.headers.getAll(key)})))`

The existing one is incorrect.

**Comment by karthikjeeyar** [comment]
@christianvogt updated the request headers

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
