### PR TITLE
fix(url): using new work item type service method

### PR DESCRIPTION
**Pull request by sanbornsen**
- fixes openshiftio/openshift.io#3383

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sanbornsen for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by jiekang** [comment]
This is a duplicate of https://github.com/fabric8-ui/fabric8-ui/pull/2843

Also discussion of openshiftio/openshift.io#3383 continued. Maybe the feature will be removed?

**Comment by jiekang** [comment]
After more discussion it's been decided that the feature will be removed and replaced. This is done in https://github.com/fabric8-ui/fabric8-ui/pull/2855

This PR (#2847) is no longer necessary.

**Comment by nimishamukherjee** [comment]
Closing this PR.

**Pull request closed without merging**
