### PR TITLE
fix(environment-widget): disable links when deployment has 0 pods

### PR DESCRIPTION
**Pull request by andrewazores**
fixes https://github.com/openshiftio/openshift.io/issues/3173

### CODE REVIEW

**Comment by andrewazores** [comment]
Note that this doesn't hide the link as suggested in the bug report, but instead makes the link falsey (null) so that the component template will still display the deployment environment name and version, but make it non-clickable.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2767-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2767-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
Huh, I guess Badger's back.

**Comment by jiekang** [comment]
I think Joshua had trouble removing it; I went ahead and checked the logs and filed an issue for some of the errors: https://github.com/fabric8io/fabric8-build-team/issues/53

Looks like it works now.

**Pull request merged**
