### PR TITLE
Issue2091 no 401

### PR DESCRIPTION
**Pull request by corinnekrych**
fixes https://github.com/openshiftio/openshift.io/issues/2091 
need to be tested before merging once pro-preview is back

### CODE REVIEW

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2485-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2485-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2485-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2485-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
I'm waiting for resolution on the issue this fixes.

**Comment by corinnekrych** [comment]
@joshuawilson since Todd agreed (see issue) I'd move forward with this ticket. Noye the backecn is already merged on master/pre-prod.
cc @xcoulon

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2485-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2485-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Do they need to be merged at the same time or just wait for the -wit PR?

**Comment by corinnekrych** [comment]
@joshuawilson backend need to be deployed first (UI stays compatible), then we can deploy UI

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2485-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2485-fabric8-ui.badger.fabric8.io

**Pull request merged**
