### PR TITLE
chore: modify _tenant page to reflect changes coming in fabric8-services/fabric8-tenant#634

### PR DESCRIPTION
**Pull request by MatousJobanek**
The PR https://github.com/fabric8-services/fabric8-tenant/pull/634 that simplifies template management changes the way of downloading tenant templates that are used for in-production testing. 
Currently, it is downloaded from Nexus, so the page contains a form for setting release versions (of che, jenkins and team templates) and Maven (Nexus) repo the templates should be downloaded from. 
When the PR is merged, then the Maven repo will not be used and the templates will be downloaded directly from a git blob of a GitHub repository. The parameters that should be set in the "update request" are read on the tenant side [here](https://github.com/fabric8-services/fabric8-tenant/pull/634/files#diff-02faf925c5b82cf2f10153260d750e4bR54). That means:
* **templatesRepoBlob** for the blob = commit sha
* **templatesRepo** repository url (optional)
* **templatesRepoDir** path to a directory that contains the templates (optional)

This PR is blocked by https://github.com/fabric8-services/fabric8-tenant/pull/634

### CODE REVIEW

**Comment by joshuawilson** [comment]
I set it to Work In Progress as you stated that it is blocked by fabric8-services/fabric8-tenant#634 
Once that is merged, please remove the ref in the title.

**Comment by MatousJobanek** [comment]
The blocking [PR](https://github.com/fabric8-services/fabric8-tenant/pull/634) has been merged, so I removed the WIP prefix. May I ask for merging this PR too - to be able to test it on prod-preview?

**Comment by MatousJobanek** [comment]
Thanks for merging it @joshuawilson 
Is there any chance that it could be promoted to prod any time soon?

**Comment by joshuawilson** [comment]
waiting on the e2e to pass

**Pull request merged**
