### PR TITLE
fix(refactor): move layout related folders into new location

### PR DESCRIPTION
**Pull request by dgutride**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-1793-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1793-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Moves of files in git need to happen in a stand alone commit. Otherwise the history gets very confusing. Please break this up into at least 2 commits.

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-1793-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1793-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
Much cleaner, thanks.

**Pull request merged**
