### PR TITLE
fix(forge-service): duplicate trailing slash

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2114-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2114-fabric8-ui.badger.fabric8.io

**Comment by vpavlin** [comment]
@corinnekrych When I try this, it fails with same error in UI and I can see 
```
GET https://forge.api.openshift.io/forge//commands/fabric8-import-git 404 (Not Found)
```
in console log - notice the double slash, but on the other side of `forge`:)

**Comment by corinnekrych** [comment]
@vpavlin try with my 2nd commit

**Comment by fabric8cd** [comment]
@corinnekrych fabric8/fabric8-ui:SNAPSHOT-PR-2114-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2114-fabric8-ui.badger.fabric8.io

**Pull request merged**
