### PR TITLE
fix(error): update layout and links for error page

### PR DESCRIPTION
**Pull request by mindreeper2420**
Remove items that are not available, hook up links and update routing

closes https://github.com/fabric8-ui/fabric8-ui/issues/1724

### CODE REVIEW

**Comment by mindreeper2420** [comment]
**Updated Screen:**
screen shot 2017-07-13 at 9 27 43 am

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1729-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1729-fabric8-ui.badger.fabric8.io

**Comment by mindreeper2420** [comment]
use this link to see the error page: https://fabric8-ui-fabric8-ui-pr-1729-fabric8-ui.badger.fabric8.io/_error

**Comment by catrobson** [comment]
Looks like the Spaces link is bringing me to _home rather than to /<username>/_spaces.

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1729-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1729-fabric8-ui.badger.fabric8.io

**Pull request merged**
