### PR TITLE
fix(test): [DO NOT MERGE] - setup to test EE tests on PRs

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-13 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-18 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@ldimaggi why is it failing?

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-19 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-24 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-25 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-26 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-27 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-28 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-29 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-31 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-32 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-34 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-35 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-36 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-37 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-38 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-39 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-40 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-41 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-42 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@ldimaggi did that just pass?

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-44 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-45 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-46 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-47 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
passed again

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-48 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-49 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-50 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-54 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-55 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-56 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-57 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-58 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-59 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-60 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-62 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-66 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-67 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-68 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-69 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-70 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-71 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-72 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-73 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-74 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-75 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-77 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-78 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-79 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-81 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-82 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-83 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-84 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-87 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-88 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-89 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-90 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-91 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-92 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-93 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-95 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-96 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-103 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-110 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-111 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-112 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-113 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-114 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-115 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2341-117 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
This appears out of date, I'm closing it. If you are still using it or working on it, please reopen.

**Pull request closed without merging**
