### PR TITLE
fix(SpacesService): add check for length of recentSpaces in loadRecent()

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses an issue that is causing E2E tests to fail where the user has no empty spaces.

The problem was the check of the profile's recent spaces within `loadRecent()`. If the contextInformation on the profile has an empty list for the recentSpaces, then the if-statement takes the branch that will try to forkJoin and will never return. Trying to create spaces or view other spaces will result in an empty list, because the initial list was never populated. The fix here is to continue with fetching spaces by id only if recentSpaces exists and is non-empty.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @aptmac for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by aptmac** [comment]
It looks like forkJoin requires a value to be emitted in order for it to complete. In this case, even if on an empty list is seems that forkJoin short-circuits because nothing gets returned.

Related discussion: https://github.com/ReactiveX/rxjs/issues/2816

**Comment by ppitonak** [comment]
When do you plan to merge this PR? Almost all Jenkins jobs are failing because of this bug.

**Comment by ibuziuk** [comment]
@joshuawilson would it be possible to merge this PR since currently che related tests before promotion to prod are also broken  - https://github.com/openshiftio/saas-openshiftio/pull/1063

**Pull request merged**
