### PR TITLE
fix(pipeline-call): adds OSIO X-App header

### PR DESCRIPTION
**Pull request by bartoszmajsak**
Fixes https://github.com/openshiftio/openshift.io/issues/4453

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @bartoszmajsak for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by bartoszmajsak** [comment]
@joshuawilson @christianvogt we need this kind of header in a lot of places and I see right now it's just copied and pasted in every Launcher service. Wouldn't it make sense to have an interceptor taking care of that and presumably token propagation?

**Comment by rohitkrai03** [comment]
@bartoszmajsak Yes, this can be converted into an interceptor which will add `X-App` header to all request going to launcher endpoint.

**Comment by bartoszmajsak** [comment]
It might need a test or two. Can't really do it this week due to travels so if anyone is willing do it I offer good :beer:

**Comment by bartoszmajsak** [comment]
@rohitkrai03 could we plan this work?

**Comment by rohitkrai03** [comment]
@bartoszmajsak Yes, we can add a planner story for this. I'll be willing to work on this. Also, you were talking about adding tests to this PR or the intercepter work?

**Comment by gastaldi** [comment]
>(Do you need this merged while the interceptor is written?)

We need this fix to update the launcher-backend production to the latest version, so yes :)

**Comment by joshuawilson** [comment]
@rohitkrai03 please create a task to deal with this in an interceptor.

**Comment by rohitkrai03** [comment]
@joshuawilson Sure, will do that.

**Comment by ppitonak** [comment]
@rohitkrai03 can you provide link to that issue here?

**Pull request merged**
