### PR TITLE
style(deployments): code cleanup

### PR DESCRIPTION
**Pull request by andrewazores**
Add type annotations, use const where appropriate, do not leave
subscriptions dangling in tests, and other code quality improvements.

### CODE REVIEW

**Comment by andrewazores** [comment]
Huh. The CI bot has a test failure like this:

```
Summary of all failing tests
FAIL src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts (11.486s)
  ● DeploymentsDonutChartComponent › Mini chart › should show mini text

    TypeError: n.querySelector is not a function

      155 |     }
      156 | 
    > 157 |     donutChartTitle = d3.select(this.chart.element).select('text.c3-chart-arcs-title');
          |                                                     ^
      158 |     if (!donutChartTitle) {
      159 |       return;
      160 |     }

```

but I don't see this locally.

**Comment by aptmac** [comment]
> Huh. The CI bot has a test failure [...] but I don't see this locally.

Neat! I see the same thing; local tests complete and pass as expected.

**Comment by andrewazores** [comment]
Oh right - I had those import changes at the back of my mind while working through the rebase, and then forgot about them at the end before pushing. Thanks, I'll go back for them now. Good catch.

**Comment by aptmac** [comment]
The test failure may be a result of an async issue somewhere, there's something similar reported at https://github.com/wallabyjs/public/issues/808

**Comment by christianvogt** [comment]
There are some intermittent test failures due to async. We can skip them for now and address them later. We skipped two yesterday and this one has the same error as one I've seen before.

**Comment by andrewazores** [comment]
@christianvogt is it just that Deployment Donut component test you're talking about? I can `x` that one out as part of this PR if you're like.

**Comment by christianvogt** [comment]
@andrewazores Yes I was talking about that one. Go ahead and `x` it out. We already `x`'d out one other test in that file yesterday.

**Pull request merged**
