### PR TITLE
unit tests for SpacesService

### PR DESCRIPTION
**Pull request by harshal-dhumal**
test case to test current space update scenario.

this commit does not cover all services provided by SpacesService.

### CODE REVIEW

**Comment by sbose78** [comment]
[test]

**Comment by harshal-dhumal** [comment]
I just saw the CI builds failed, investigating.

**Comment by harshal-dhumal** [comment]
In test case I accessed private variable of spacesService and thiscaused issue while generating build.
Will submit updated PR.

**Comment by sbose78** [comment]
[test]

**Comment by joshuawilson** [comment]
please rebase

**Comment by joshuawilson** [comment]
@harshal-dhumal can you please ping me on https://chat.openshift.io/developers/ so I can help you with the git rebase/merge. we have a few things to clean up before this can be merged.

**Pull request closed without merging**
