### PR TITLE
fix(profile): update layout for Update Profile page

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the Update Profile page to reflect the new layout design

closes https://github.com/fabric8-ui/fabric8-ui/issues/1691 and https://github.com/fabric8-ui/fabric8-ux/issues/534

Note: The "Update Tenant" button will be removed at a later date.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
**Updated Layout:**
screen shot 2017-07-10 at 2 09 07 pm

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1696-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1696-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-1696-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1696-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
@mindreeper2420 the size of the avatar needs to set, mine is too large and blowing out the layout.
profile-openshift io

**Comment by mindreeper2420** [comment]
@joshuawilson interesting - I used the fabric8cd link and my profile picture is fine.

**Comment by joshuawilson** [comment]
well, to be fare, I just checked and it does the same thing in prod

**Comment by catrobson** [comment]
Mine looks fine as well, but once you click "Link Profile Picture" it blows up to be too large.

**Comment by joshuawilson** [comment]
I'm going to merge this as is and we can have another bug/PR fix the image size.

**Comment by catrobson** [comment]
@mindreeper2420 can we add some space between the last of the main fields and the "Advanced" headline:
image

You sort of miss that there is another section with how close they are right now.

**Pull request merged**
