### PR TITLE
refactor(deployments): remove unused IDeploymentsService

### PR DESCRIPTION
**Pull request by andrewazores**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2266-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2266-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-ui.badger.fabric8.io

**Comment by andrewazores** [comment]
The goal was to use the interface type in all injected sites using the service and use the InjectionToken to get that instance via DI, so that the coupling between service implementation and service consumers could be loosened. This would also help with creating mock services in tests, since the mock service class would only need to implement what's specified in the interface and not also need to mirror the public and private properties of the real implementation, including implementation details like the "headers" property or even the http client. It's still doable without this of course, but AFAICT only by foregoing some type safety checks.

This code is being removed for cleanup following this rejected PR: https://github.com/fabric8-ui/fabric8-ui/pull/2250

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2266-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2266-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-ui.badger.fabric8.io

**Pull request merged**
