### PR TITLE
fix(settings): Redirect user to appropriate feature opt in page

### PR DESCRIPTION
**Pull request by chrislessard**
This patch changes the route used by the feature warning page to redirect users to the feature opt in page under their profile settings, instead of their profile.

Fixes: https://github.com/openshiftio/openshift.io/issues/3260

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @chrislessard for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by joshuawilson** [comment]
@chrislessard you know that if the settings pages gets put behind a feature flag then this will need that too?

**Pull request merged**
