### PR TITLE
fix(test): force a build to debug login errors

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2233-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2233-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
do you need this merged to test something?

**Comment by joshuawilson** [comment]
@ldimaggi wait, merge, or close?

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2233-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2233-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
