### PR TITLE
improve build speeds by using thread-loader and cache-loader in monorepo

### PR DESCRIPTION
**Pull request by christianvogt**
Implements the same performance improvements in the monorepo as per PR https://github.com/fabric8-ui/fabric8-ui/pull/3406

Also includes updates to the monorepo package of `fabric8-ui` needed to perform proper testing of the builds to validate the changes to the webpack config. Specifically I needed to apply the `postinstall` font swap that is currently performed against patternfly. I took a different approach by running a node script to benefit from node module loading algorithm such that the patternfly module could be properly found in a monorepo scenario if patternfly was installed in the monorepo root directory.

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @christianvogt for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
