### PR TITLE
WIP: fix(settings): Add public/private email options

### PR DESCRIPTION
**Pull request by mindreeper2420**
Add option to set your email to either public or private.

related to https://github.com/fabric8-ui/fabric8-ux/issues/841

**Note:** This is just the HTML/CSS and does not include the specific functionality for setting a user's email to public or private.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2461-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2461-fabric8-ui.badger.fabric8.io

**Comment by mindreeper2420** [comment]
Do Not Merge until PR is updated. Radio buttons are misaligned in Chrome.

**Comment by mindreeper2420** [comment]
@catrobson I've updated the PR to take care of the alignment issues.

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2461-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2461-fabric8-ui.badger.fabric8.io

**Comment by catrobson** [comment]
Much better, thanks @mindreeper2420!

**Comment by joshuawilson** [comment]
@mindreeper2420 is this ready to be merged? or do we need to wait for supporting code?

**Comment by alexeykazakov** [comment]
no, it's not ready to be merged. It's just dead HTTML/CSS. We have to add supporting code before merging.

**Comment by sbose78** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2489 has the code changes + the html/css copied over from this PR.

**Comment by mindreeper2420** [comment]
I'll close this PR, as it is in the PR that @sbose78 referenced.

**Pull request closed without merging**
