### PR TITLE
fix(profile): disable profile update if bio char count increases max limit

### PR DESCRIPTION
**Pull request by rohitkrai03**
Fixes https://github.com/openshiftio/openshift.io/issues/3709

- Removes the `blockInputAtMaxLimit` flag so that there is no auto truncation of characters if over max limit.
- Using `onOverCharsMaxLimit` validates the bio input. If the input is over char limit then the profile update is disabled.
- The PR contains changes related to formatting because of prettier changes on save.

Screenshots - 

screenshot 2018-12-19 at 1 09 14 am

screenshot 2018-12-19 at 1 09 35 am

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @rohitkrai03 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by christianvogt** [comment]
This is probably not your doing but why is the character count red when I still have characters left to enter:
image

Is it a warning that I'm close to my max? Red screams error and not a warning....

**Comment by christianvogt** [comment]
The character count is at 255 remaining when you refresh the page even though there is a bio already present:
image

**Comment by christianvogt** [comment]
@rohitkrai03 I'm fine with the red color. But the character count needs to be fixed. If it's a problem with patternfly directive, either find a work around, get a fix in patternfly, or fork it and fix it in our code.

**Comment by rohitkrai03** [comment]
This is where we can traack the issue for char count bug - https://github.com/openshiftio/openshift.io/issues/1882. We can move ahead with this one.

**Pull request merged**
