### PR TITLE
fix(card): Keep Create Space icon in Card Header

### PR DESCRIPTION
**Pull request by mindreeper2420**
Keep the Create Space icon in the Card Header for Recent Spaces card, whether the Card is in an empty state or showing Recent Spaces.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
This PR closes https://github.com/fabric8-ui/fabric8-ux/issues/809 and https://github.com/openshiftio/openshift.io/issues/1579.

Please wait for review before merging. Thanks!

**Comment by catrobson** [comment]
@mindreeper2420 I don't want to just do this for the recent spaces card header - I'd like to make the change to all cards across our dashboards if we're going to make this update.

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2386-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2386-fabric8-ui.badger.fabric8.io

**Comment by mindreeper2420** [comment]
@catrobson Currently, this card and the Pipelines card (on the Space Dashboard) do not have the "+" as a constant. I can update that Card as well, if desired.

**Comment by catrobson** [comment]
@mindreeper2420 please do.

**Comment by mindreeper2420** [comment]
screen shot 2018-01-12 at 11 25 23 am
screen shot 2018-01-12 at 11 30 03 am

**Comment by mindreeper2420** [comment]
@catrobson Updated with the icon for the Pipelines page.

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2386-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2386-fabric8-ui.badger.fabric8.io

**Pull request merged**
