### PR TITLE
feat(deployments): add network requests sparkline

### PR DESCRIPTION
**Pull request by andrewazores**
closes https://github.com/openshiftio/openshift.io/issues/1787

screenshot-20180116125722

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2402-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2402-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
@andrewazores I'm not actually sure we will have network requests data to show. @stooke or @ebaron could one of you verify?

**Comment by ebaron** [comment]
@jiekang @andrewazores Unfortunately there is no underlying data we can query to count network requests.

**Comment by andrewazores** [comment]
@catrobson ^ we're unable to implement the "Requests" Sparkline.

**Comment by jiekang** [comment]
I suppose it would need changes in Openshift or Kubernetes to provide the data.

**Comment by catrobson** [comment]
@andrewazores ok, let's continue ahead without it, and we can create an issue if we find users really need this information to work with the OpenShift team to resolve this.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2402-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2402-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
