### PR TITLE
fix(#1698): context no longer contains "forge"

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@gastaldi fabric8/fabric8-ui:SNAPSHOT-PR-2338-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2338-fabric8-ui.badger.fabric8.io

**Comment by gastaldi** [comment]
Quickstarts are working fine with this PR

**Comment by gastaldi** [comment]
[merge]

**Pull request merged**
