### PR TITLE
fix(spacedelete): only allow creator to delete space

### PR DESCRIPTION
**Pull request by dgutride**
Fixes - https://github.com/fabric8-ui/fabric8-ux/issues/505

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dgutride snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1612-fabric8-platform.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dgutride snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1612-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
It looks like this should hide the trash can for spaces I don't own. If that is the case it doesn't work. It currently does the same thing as production. 
I'm seeing `PATCH https://api.openshift.io/api/users 401 (Unauthorized)` which might be related.

**Comment by fabric8cd** [comment]
@dgutride snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1612-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dgutride snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1612-fabric8-ui.badger.fabric8.io

**Pull request merged**
