### PR TITLE
feat(deployments): disable "Scale Up" when environment quotas are rea…

### PR DESCRIPTION
**Pull request by andrewazores**
…ched

fixes https://github.com/openshiftio/openshift.io/issues/3345

screenshot from 2018-04-27 18-15-43

This PR also does some cleanup of the component, removing an unused variable (`scalable`) and tracking/unsubscribing Subscriptions. The feature is in the new `atQuota` property and the `combineLatest` Observable in ngOnInit that sets it, along with the template changes to disable the button and change the tooltip text based on `atQuota`.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2827-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2827-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
@andrewazores 
When manual user testing, I am still able to trigger the scale up action when it's set to Disabled.

I think `scalable` was being used and may have been inadvertently broken somewhere along the line.

**Comment by andrewazores** [comment]
@jiekang fixed, that was silly. Thanks for being more thorough with your manual testing than I was. I saw it looked disabled and just figured it was... whoops.

**Comment by jiekang** [comment]
@andrewazores 

What do you think about the check incorporating: It should prevent users from scaling up past the quota, assuming that each scale would add the fixed amount for application. This would cover the ability for a user to start from 0/1 applications, and quickly click the scale up button to 5. This would be similar to how it already doesn't let users scale below 0, just the constant changes based on data from the last poll cycle info.

I guess handling the various scenarios can become complicated. And there's the timing, maybe a particularly fast user (automated clicks?) could get past that kind of check anyways. Could be another issue if you think it might be worth looking into.

**Comment by andrewazores** [comment]
@jiekang yes, that's related to what Todd and I were just discussing on the related issue (https://github.com/openshiftio/openshift.io/issues/3345). If we can query for how much quota will be consumed by a pod, then we can incorporate this type of logic.

Marking as "Do not merge" as Todd has asked for confirmation from Cat first.

**Comment by jiekang** [comment]
I think for an interm of quota consumed by a pod, it would be accurate to divide the used quota by the number of pods. Is it possible to scale a deployment up and have different quotas taken by the individual pods of that deployment? The UI developed for the OSO console suggests scaling a pod involves a complete replica of the deployment.

**Comment by andrewazores** [comment]
I believe each pod would have the same allotment as the rest for a given deployment, but perhaps that's not always the case? Even if so, that approach wouldn't work for a deployment that currently has 0 pods, since we wouldn't be able to infer what the usage of each pod is at that point, even though the behaviour we're talking about would disable the "scale up" button if a single pod would exceed the quota. It's possible as another partial solution, but I'm not sure about it.

**Comment by fabric8cd** [comment]
@andrewazores fabric8/fabric8-ui:SNAPSHOT-PR-2827-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2827-fabric8-ui.badger.fabric8.io

**Comment by jiekang** [comment]
Ah yes, excellent point regarding the 0 case. Definitely needs API work then, right?

**Comment by andrewazores** [comment]
Yea. https://github.com/openshiftio/openshift.io/issues/3345#issuecomment-385568945

**Pull request merged**
