### PR TITLE
fix(profile): Verify OSO token status while retrieving OSO token in profile overview

### PR DESCRIPTION
**Pull request by rohitkrai03**
Related to https://github.com/fabric8-services/fabric8-auth/issues/320

- Adds getOpenShiftStatus()  in providerService to get auth token with new param `force_pull=true`.

- Adds updateOpenShiftStatus() in connected-accounts.component which gets called in ngOnInit()

- Updated test cases for the above changes.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rohitkrai03 fabric8/fabric8-ui:SNAPSHOT-PR-2613-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2613-fabric8-ui.badger.fabric8.io

**Comment by sbose78** [comment]
[test]

**Comment by sbose78** [comment]
Verified that when the profile page loads, the browser makes a call to : 

```
Request URL:https://auth.prod-preview.openshift.io/api/token?force_pull=true&for=https://api.free-stg.openshift.com/
Request Method:GET
Status Code:200 OK
```

**Comment by fabric8cd** [comment]
@rohitkrai03 fabric8/fabric8-ui:SNAPSHOT-PR-2613-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2613-fabric8-ui.badger.fabric8.io

**Comment by dgutride** [comment]
@joshuawilson  - code looks good, not sure why the build is hung up

**Comment by joshuawilson** [comment]
[test]
The ci.centos build is hung because rohitkrai03 has not been added to the approved list. You can kick the build off with the `[test]` command.

**Comment by fabric8cd** [comment]
@rohitkrai03 fabric8/fabric8-ui:SNAPSHOT-PR-2613-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2613-fabric8-ui.badger.fabric8.io

**Pull request merged**
