### PR TITLE
fix(version): update fabric8-planner to 0.29.1

### PR DESCRIPTION
**Pull request by fabric8cd**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1859-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1859-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1859-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1859-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
It fails with 
`Unable to create new service: PhantomJSDriverService`
and 
`Functional tests FAIL`

Since we haven't turned on FT, I don't know why this is happening.

**Comment by joshuawilson** [comment]
@nimishamukherjee @michaelkleinhenz maybe you can take a look at this.

**Comment by joshuawilson** [comment]
[test]

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1859-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1859-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@fabric8cd fabric8/fabric8-ui:SNAPSHOT-PR-1859-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1859-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
