### PR TITLE
fix(rxjs): change listening behavior for space broadcast

### PR DESCRIPTION
**Pull request by dgutride**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2413-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2413-fabric8-ui.badger.fabric8.io

**Comment by dgutride** [comment]
Breaking service is in planner: 
getLabels(): Observable<LabelModel[]> {
    return this.spaces.current.switchMap(
      currentSpace => this.http.get(currentSpace.links.self + '/labels')
    ).map (response => {
      return response.json().data as LabelModel[];
    })
  }

app/services/label.service.ts  - currentSpace.links isn't always present and this shouldn't be listened to if disposing

**Comment by corinnekrych** [comment]
When testing from badger, I got this:
when going to Planner we got this Exception:
```
ERROR TypeError: Cannot read property 'attributes' of undefined
```
bc of missing null test in https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html#L28
=> we then end-up with duplicate menu.

**Comment by corinnekrych** [comment]
@dgutride https://github.com/dgutride/fabric8-ui/pull/1 to fix the problem on attributes.

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2413-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2413-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2413-4 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2413-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dgutride fabric8/fabric8-ui:SNAPSHOT-PR-2413-5 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2413-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
is this something we still want to merge?

**Pull request closed without merging**
