### PR TITLE
fix(locator): Generate valid URL when only suffix is configured

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
6000% code coverage. LGTM

gif-dancing-celebrate-celebration-dance-ecstatic-happy-happy-dance-joy-success-woo-hoo-gif

**Comment by fabric8cd** [comment]
@aslakknutsen fabric8/fabric8-ui:SNAPSHOT-PR-2217-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2217-fabric8-ui.badger.fabric8.io

**Comment by aslakknutsen** [comment]
Nah, my default parameters didn't work with Injection.. 

```js
Uncaught Error: Can't resolve all parameters for ApiLocatorService: ([object Object], ?, ?).
    at syntaxError (fabric8-ui-global-overrides.less:2)
    at CompileMetadataResolver._getDependenciesMetadata (fabric8-ui-global-overrides.less:2)
    at CompileMetadataResolver._getTypeMetadata (fabric8-ui-global-overrides.less:2)
    at CompileMetadataResolver._getInjectableMetadata (fabric8-ui-global-overrides.less:2)
    at CompileMetadataResolver.getProviderMetadata (fabric8-ui-global-overrides.less:2)
    at fabric8-ui-global-overrides.less:2
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (fabric8-ui-global-overrides.less:2)
    at CompileMetadataResolver.getNgModuleMetadata (fabric8-ui-global-overrides.less:2)
    at JitCompiler._loadModules (fabric8-ui-global-overrides.less:2)
```

**Comment by fabric8cd** [comment]
@aslakknutsen fabric8/fabric8-ui:SNAPSHOT-PR-2217-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2217-fabric8-ui.badger.fabric8.io

**Comment by aslakknutsen** [comment]
The injection works now.

**Comment by fabric8cd** [comment]
@aslakknutsen fabric8/fabric8-ui:SNAPSHOT-PR-2217-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2217-fabric8-ui.badger.fabric8.io

**Pull request merged**
