### PR TITLE
patternfly-ng: remove deprecations

### PR DESCRIPTION
**Pull request by dlabrecq**
Removes deprecated and unused patternfly-ng module imports.

Resolves https://github.com/openshiftio/openshift.io/issues/2704

### CODE REVIEW

**Comment by jiekang** [comment]
The change to the package-lock.json file is massive relative to the rest of this PR. Could you clarify where it's coming from? Just taking a look it seems to have a lot more exact versions instead of caret ranges than which sounds good for stability to me.

**Comment by dlabrecq** [comment]
That's what `npm install` generated (npm 5.3.0/node 8.3.0). I assumed we should be updating the package-lock when dependencies are updated. Should I remove it?

**Comment by jiekang** [comment]
I like the changes there but I don't know when package-lock.json updates are supposed to be made. If someone else could chime in I'd appreciate it. @joshuawilson Is it okay?

**Comment by andrewazores** [comment]
Same, actual changes look fine but I don't know how we want to handle the package lock file.

**Comment by joshuawilson** [comment]
The package-lock should (must) be updated when the package is changed. 

Please rebase.

**Comment by dlabrecq** [comment]
Rebased with latest changes

**Pull request merged**
