### PR TITLE
[DO NOT MERGE] use temporary fork of pipeline library

### PR DESCRIPTION
**Pull request by jstrachan**
this is to try fix up the PR UI stuff

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-2227-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2227-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-2227-6 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2227-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-2227-7 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2227-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-2227-8 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2227-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
What is the status of this? Do we close it or merge it? 
cc @ldimaggi

**Comment by ldimaggi** [comment]
I think that we can close this one - I think that it was made obsolete by:  https://github.com/fabric8io/fabric8-pipeline-library/pull/371

**Comment by fabric8cd** [comment]
@jstrachan fabric8/fabric8-ui:SNAPSHOT-PR-2227-9 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2227-fabric8-ui.badger.fabric8.io

**Pull request closed without merging**
