### PR TITLE
show proper message on analytics widget when no pipeline exists

### PR DESCRIPTION
**Pull request by jyasveer**

### CODE REVIEW

**Comment by jyasveer** [comment]
https://github.com/openshiftio/openshift.io/issues/563

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-1882-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1882-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
The commit needs proper syntax.

**Comment by jyasveer** [comment]
@joshuawilson can you please review it now ?

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-1882-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1882-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
[test]

**Comment by joshuawilson** [comment]
I can't reproduce the error this is fixing. I see "No Recommendations" listed during a pipeline build in the current version. In this update I see an empty state, as if there had never been a pipeline. 

The current view looks to make more sense to me.

**Comment by jyasveer** [comment]
I am attaching my screenshot here to show my changes. It would show "No Results Found" when we dont have pipeline yet. I would change to "No Recommendations" or show a list of recommendations if any. You would also mark that there is no dropdown present when a build starts and this message is shown until a pipeline is available.
This screenshot i have taken from the snapshot which is generated and given above.
https://fabric8-ui-fabric8-ui-pr-1882-fabric8-ui.badger.fabric8.io
screen shot 2017-08-18 at 1 27 57 pm

**Comment by fabric8cd** [comment]
@jyasveer fabric8/fabric8-ui:SNAPSHOT-PR-1882-3 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1882-fabric8-ui.badger.fabric8.io

**Comment by joshuawilson** [comment]
This means that if I have 3 applications and I run the pipeline for one of them, you are going to remove the recommendations for the others?

**Comment by joshuawilson** [comment]
[test]

**Comment by jyasveer** [comment]
all the pipelines will be available in the dropdown. if i run the pipeline for one others still remain

**Pull request merged**
