### PR TITLE
NotificationService: replace ngx-widgets import with patternfly-ng

### PR DESCRIPTION
**Pull request by dlabrecq**
NotificationService is using an old import from ngx-widgets and needs to use patternfly-ng.

### CODE REVIEW

**Comment by dlabrecq** [comment]
Please wait to merge.

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-1835-1 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1835-fabric8-ui.badger.fabric8.io

**Comment by fabric8cd** [comment]
@dlabrecq fabric8/fabric8-ui:SNAPSHOT-PR-1835-2 fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1835-fabric8-ui.badger.fabric8.io

**Pull request merged**
