### PR TITLE
fix(spaces): re-introduce missing 'pageSize' attribute when fetching user's spaces

### PR DESCRIPTION
**Pull request by aptmac**
This PR addresses a side-effect of my recent PR [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3381) to add shared spaces to the 'Spaces' page.

The service function used to retrieve spaces by username has an optional parameter `pageSize`, that defaults to 20 if not specified. The former 'Space' page had a variable called `pageSize` hold a value of '2000' [[1]](https://github.com/fabric8-ui/fabric8-ui/pull/3381/files#diff-751600f87e785e8a26f9e457250b05b1L45), and I had forgotten to replace the `pageSize` value when cleaning up the component. Instead of just setting an arbitrary large number such as '2000' I thought it may be a good idea to use the number returned by `user-spaces.service.getInvolvedSpacesCount()` because that total will encompass the number of spaces the user collaborates on and owns, which will be a closer representation of how many spaces to ask for when calling `getSpacesByUser()`.

[0] https://github.com/fabric8-ui/fabric8-ui/pull/3381
[1] https://github.com/fabric8-ui/fabric8-ui/pull/3381/files#diff-751600f87e785e8a26f9e457250b05b1L45

### CODE REVIEW

**Comment by aptmac** [comment]
> Looks fine. I wonder about page performance though - there are a lot of potentially wasted requests going on with various subscriptions through the UserSpacesService at this point. Do you think that service can implement some form of caching as a followup?

Hm, yeah I think there could be a way to keep some information around so it doesn't need to be fetched every time. Perhaps listen for broadcasted events pertaining to space creation/editing/deletion and only then update some cached `sharedSpaces` list that gets initialized with the service? Also, I recall hearing about some sort of different way with talking to the backend, perhaps related to this [comment [0]](https://github.com/openshiftio/openshift.io/issues/4326#issuecomment-430379021)? If there was a better way to get this information (like shared spaces) from the database then we wouldn't need multiple functions chained together to get the information.

[0] https://github.com/openshiftio/openshift.io/issues/4326#issuecomment-430379021

**Comment by andrewazores** [comment]
Sure, something like that might be workable. Even just temporally caching the UserSpacesResponse would do some good, since those values aren't likely to be rapid changing. getInvolvedSpacesCount could also be refactored to not actually fire off a new request but use a cached response from the last time getInvolvedSpaces was called (if any - if not then do fire off a request), for example.

**Comment by joshuawilson** [comment]
Please talk to @christianvogt since he has been planning how to manage state.

**Pull request merged**
