### PR TITLE
fix(work-item-widget): work-item-widget displaying bar chart now

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes https://github.com/openshiftio/openshift.io/issues/4057

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @divyanshiGupta for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by andrewazores** [comment]
Code looks good but please add some tests.

**Comment by divyanshiGupta** [comment]
@andrewazores I tried changing some test cases so that it handles case sensitive states of work item. But due to an issue with current version of PhantomJS that we use `string.localeCompare` does not work as intended with `options` - https://github.com/ariya/phantomjs/issues/14496

**Comment by andrewazores** [comment]
Oh... that's very unfortunate. Okay then.

**Comment by alien-ike** [comment]
Hey @andrewazores! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by andrewazores** [comment]
@joshuawilson ^

**Comment by divyanshiGupta** [comment]
@joshuawilson can we merge this PR?

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
