### PR TITLE
Email Verification - Fix image in build and link to dashboard

### PR DESCRIPTION
**Pull request by SMahil**
Fix image in build and link to dashboard

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @SMahil for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by rohitkrai03** [comment]
@SMahil Code looks good to me. But i found a related but different bug that's there on prod as well. While redirecting to some page from an error page when there is some error param in URL, the redirect doesn't work for some reason. 

So, clicking the take me home button on https://openshift.io/_error works fine but for https://openshift.io/_error?error=some_error it doesn't.

cc: @joshuawilson

**Comment by joshuawilson** [comment]
@rohitkrai03 do you think we could add a unit test to check for that?

**Comment by rohitkrai03** [comment]
@joshuawilson Adding a test might be a bit tricky here because while debugging i could see the router is redirecting the URL but the desired component somehow fails to render. So, i am not sure how to reproduce this thing in unit test. 
Also, i've created an issue related to this - https://github.com/openshiftio/openshift.io/issues/3144

**Pull request merged**
