### PR TITLE
fix(launcher): update ngx-launcher to 1.0.16

### PR DESCRIPTION
**Pull request by vikram-raj**
This version contains these fixes.
1. openshiftio/openshift.io#3443
2. Create app flow of this issue https://github.com/openshiftio/openshift.io/issues/4140
3. openshiftio/openshift.io#3927
4. https://github.com/fabric8-launcher/ngx-launcher/issues/349 and https://github.com/openshiftio/openshift.io/issues/3997

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@joshuawilson how do we test such updates?

**Comment by bartoszmajsak** [comment]
@vikram-raj as there is a newer version out can we update this PR to have that shipped instead.

@joshuawilson how we can make merging PRs smoother?

**Comment by joshuawilson** [comment]
In what way @bartoszmajsak?

@vikram-raj please rebase

**Comment by bartoszmajsak** [comment]
@joshuawilson In a way that library update does not hang 5d as a PR :) But it is general observation of PR-to-master time. We should think about how to make that easier (boils down to ensuring we don't break things... but anyway).

**Comment by vikram-raj** [comment]
@bartoszmajsak @joshuawilson  I updated this PR with the latest version of ```ngx-launcher```.

**Comment by joshuawilson** [comment]
The `continuous-integration/jenkins/pr-merge` build step is not required. I've just disabled that webhook, so it should be gone in future PRs.

**Pull request merged**
